### ISSUE TITLE
Mystical Site

### ISSUE THREAD

**Issue by dredger23** [ldtteam/MinecoloniesWiki#1003]
## Page(s)
[](https://wiki.minecolonies.com/source/buildings/mysticalsite)

## Information Missing
What do I need to build first to get it to show up with the wand?

**Comment by dredger23** [comment]
https://wiki.minecolonies.com/source/buildings/mysticalsite

**Comment by Thodor12** [comment]
This is the wiki repository. For questions with the mod use the main repository discussion, or go to Discord.

That being said, there are no requirements for the mystical site, other than research.
