### ISSUE TITLE
Why you need a courier bed?

### ISSUE THREAD

**Issue by StudentGI** [ldtteam/MinecoloniesWiki#1005]
## Page(s)
There's no information about the bed in the courier hut

## Information Missing
Why does the courier hut need a bed? They live separately in houses anyway. Or I don't understand something and it is possible to put them in the courier hut?

((1.16.5)) I know this version doesn't support the mod. 
but I want to know about the bed.
![2023-10-14_20 46 31](https://github.com/ldtteam/MinecoloniesWiki/assets/66908451/ce58e600-7481-44a7-8965-97d702124523)

**Comment by MotionlessTrain** [comment]
The wiki doesn't give any information about the bed, as there is no functional reason for that bed to be there.
That bed is just decoration

**Comment by StudentGI** [comment]
ok

**Comment by StudentGI** [comment]
Ok
