### ISSUE TITLE
Missing English names datapack

### ISSUE THREAD

**Issue by DN2048** [ldtteam/MinecoloniesWiki#1007]
## Page(s)
https://wiki.minecolonies.ldtteam.com/source/misc/customcitizennames

## Information Missing
Missing the official English datapack for the citizen names to be used as template.

**Comment by Thodor12** [comment]
This page has been updated, so every datapack now works the same, all can be used as templates.

Alternatively the datapacks page actually tells you how to make them:
https://minecolonies.com/wiki/tutorials/datapacks#citizen-names
