### ISSUE TITLE
Builder only builds level 1 blueprints

### ISSUE THREAD

**Issue by Vertical-Recoil** [ldtteam/MinecoloniesWiki#1008]
## The Issue
I made a blueprint of a Sawmill, and since my builders hut is at level 3, i started the blueprint at level 3. The builder proceeded to build the Sawmill at level 1.

Makes it an issue once you have a mid-developed town and don't want to spend time gathering the low-tier resources to make the level 1 stuff again.

## Mod Version 1.16.5.
This may have been resolved in newer versions. Can you please confirm!

**Comment by MotionlessTrain** [comment]
This is intended behaviour.

Also, this is the issue tracker of the wiki of minecolonies, not of the mod itself

**Comment by Thodor12** [comment]
1.16.5 is not supported, and this is the wrong place to make issues for mod problems.
