### ISSUE TITLE
Material Lists for Buildings

### ISSUE THREAD

**Issue by zombiekekshd** [ldtteam/MinecoloniesWiki#1009]
## Page Description

I would like a page added where you can get the materials needed for every building and every style
## Reason

i want to know how many ressources i have to far for every build, so i can farm the Items in advance. This would be very useful for survival builders and players like me, because i always have to travel thousands of blocks for some Items.

**Comment by Thodor12** [comment]
Impossible, as there is no singular style to do this for, also there's load of unofficial styles that we do not keep track of.
