### ISSUE TITLE
Multiple pages unavailable

### ISSUE THREAD

**Issue by mborenst** [ldtteam/MinecoloniesWiki#1011]
## Description

Hey, I was scrolling through the wiki and trying to learn how the systems work and strategizing how to build up my colony the best when I found that many pages in the jobs and buildings categories are unavailable. They read 503 Service Temporarily Unavailable followed by a line and the blurb nginx. Wanted to flag this issue as someone who finds your wiki a valuable resource and the mod very fun.

**Comment by Thodor12** [comment]
#1010
