### ISSUE TITLE
Forester's Hut missing leveling info

### ISSUE THREAD

**Issue by dunsterville** [ldtteam/MinecoloniesWiki#1014]
## Page(s)

https://wiki.minecolonies.com/source/buildings/lumberjack

## Information Missing

What leveling up the building does. I have no idea what leveling does except give it the ability to use better tools.

**Comment by Thodor12** [comment]
Unless someone wants to correct me, there is literally nothing else he does

**Comment by dunsterville** [comment]
Alright, sounds good, will mark this closed.
