### ISSUE TITLE
Courier not Filling Builder Hut Required Resources

### ISSUE THREAD

**Issue by PlainSimpleGarak** [ldtteam/MinecoloniesWiki#1023]
I have a new colony with a few early huts: Builder's, Town Hall, Tavern, Restaurant, Warehouse, Courier Hut.
The courier is filling "Minimum Stock" orders from the builder's hut, but not anything from the "Required Resources" section.
As an example, the builder is currently building a forester's hut. The Warehouse has all required resources, yet the courier is idle.

**Comment by Thodor12** [comment]
This is the repository for the wiki, not the mod itself.

Builders do not request everything they need at once, they request it in small batches as and when they need it, please go to Discord if you have questions rather than filing bug reports.
