### ISSUE TITLE
Styles of the Mine Colonies

### ISSUE THREAD

**Issue by M0gik** [ldtteam/MinecoloniesWiki#1025]
## Information Missing

Maybe you guys should add in the different styles of the colonies, like the dark oak , brich, oak and etc in the wiki, and the wood required, that would be nice so we all can know where to find the place and build it cuz now it doesn't feel like how and what i should have to build my town. Like example, i want to make an underground town but hey I don't even know what wood is needed, and this island have only brich wood, so yea that's the big issue on i can't find the styles of the town and wood requirement.

**Comment by Thodor12** [comment]
Asked before, no we won't do this, information regarding a specific style (out of god knows how many exists) is not information that should appear on the wiki.
