### ISSUE TITLE
Curseforge Launcher Help links to 404 page

### ISSUE THREAD

**Issue by LakenDeal007** [ldtteam/MinecoloniesWiki#1027]
It seems like every page on the website that helps with curseforge launch is down. Maybe Im a noob and overlooking something, but I am having trouble with launching the mod. I think it has something to do with multiple versions of the mods and the game but I can't figure it out currently. I hope the links are restored soon.

**Comment by Thodor12** [comment]
Duplicate of #823, nobody had just looked into it yet, we need someone to write it at some point
