### ISSUE TITLE
Ancient tome image is broken

### ISSUE THREAD

**Issue by Talyda** [ldtteam/MinecoloniesWiki#1057]
https://minecolonies.com/wiki/items/ancient_tome

This page, the image should show the tome as it appears normally, and how it appears glowing for a raid (at least it used to!)

**Comment by Thodor12** [comment]
But it does? There are 2 images on display.

**Comment by Talyda** [comment]
Neither of them are animated.
And neither of them are of the glow that the tome gets when there is a raid on the way. There used to be an animated one

**Comment by Talyda** [comment]
![image](https://github.com/ldtteam/MinecoloniesWiki/assets/17323101/6fda63af-4362-4a74-8f29-ebcfd8e7d6ae)
This is how it looks when there is not a raid, the glow is very different when there is going to be one

**Comment by Talyda** [comment]
Please to be reopening?

**Comment by Talyda** [comment]
Found the image here!
https://github.com/ldtteam/MinecoloniesWiki/commit/638c261f043e448b0324c62c6ec95268b7f95b3a
