### ISSUE TITLE
Doctor on Worker System

### ISSUE THREAD

**Issue by Captain-Vega-Saiph-Aitair** [ldtteam/MinecoloniesWiki#1061]
## Page(s)
Worker System

## Information Missing
Table showing different type of workers is missing Doctor.

**Comment by MotionlessTrain** [comment]
They are called "healer", no doctor

**Comment by Thodor12** [comment]
According to the code in the mod they should be called doctors
```json
"com.minecolonies.job.healer": "Doctor",
```

**Comment by MotionlessTrain** [comment]
In that case, it look like the wiki is inconsistent with minecolonies. It is consistently called healer on the wiki (on the Hospital page too)

**Comment by Thodor12** [comment]
That's because all of the names are generated using the name in the wiki, where it's called Healer
