### ISSUE TITLE
Quarries only in some packs.

### ISSUE THREAD

**Issue by Captain-Vega-Saiph-Aitair** [ldtteam/MinecoloniesWiki#1062]
## Page(s)
Quarry

## Information Missing
The Quarry is only available in some packs. It is in the Minecolonies Original pack, for this mod pack It is under Infrastructure > Mineshafts

**Comment by Thodor12** [comment]
There is no reasonable expectation that all packs have to provide all buildings, many styles are community made and we cannot force anyone to make them.

Not to mention this is the wiki repository, and not the mod repository, closing.

**Comment by Captain-Vega-Saiph-Aitair** [comment]
Suggesting to add the information about this to your wiki. It is not easy to setup the Quarry.

-Sheldon

________________________________

**Comment by Thodor12** [comment]
No, we're not going to add some overview of styles and what they're missing, that's up to pack creators to handle. Not the wiki.
