### ISSUE TITLE
Restaurant Cooking food

### ISSUE THREAD

**Issue by Zanforian** [ldtteam/MinecoloniesWiki#1064]
## Page(s)

Restaurant
## Information Missing

If the restaurant has raw food (like uncooked meat or potatoes) in it's storage the cook will automatically start cooking them, regardless of if they have the smelting recipe or not. This means that the restaurant should not be assigned a minimum amount of raw food, as they will constantly cook it into cooked food, and request more raw food.

**Comment by Thodor12** [comment]
We don't include specific usage details like this on the wiki.
