### ISSUE TITLE
Link to Famer Worker page broken

### ISSUE THREAD

**Issue by paul2krum** [ldtteam/MinecoloniesWiki#1075]
Not able to display worker pages (Farmer in particular)  when requested it always displays the Farm Hut page

**Comment by paul2krum** [comment]
I have now attempted to open other worker pages and the page displays for a few seconds and immediately goes to the associated hut page,  not allowing me to read the worker page requested.

**Comment by MotionlessTrain** [comment]
The worker pages have been merged with the building pages, as they didn't provide much information themselves (besides the info box, which has been moved to the building page as well)
