### ISSUE TITLE
"See the smelter's page"

### ISSUE THREAD

**Issue by JohanniklasLp** [ldtteam/MinecoloniesWiki#1080]
## Page(s)
https://minecolonies.com/wiki/buildings/smeltery

## Inaccuracy
"See the Smelter's page for how their strength affects the output."
There is no Smelter's page. Clicking on Smelter in the workers tab links back to the Smeltery page.

## Additional Information
The Smelter's page seems to have existed at some point, seeing how it is linked in https://github.com/ldtteam/MinecoloniesWiki/issues/955, but it now leads to a 404

**Comment by Thodor12** [comment]
Intended, workers pages no longer exist and have been merged.

**Comment by JohanniklasLp** [comment]
The smeltery page does not mention how strength affects the output, and the mention of the smelter's page should not be there either seeing how said page does not exist
