### ISSUE TITLE
Undertaker page missing

### ISSUE THREAD

**Issue by FlimsyCarrot** [ldtteam/MinecoloniesWiki#1082]
## Page(s)

Worker - Undertaker (Graveyard Worker)

## Information Missing

The Undertaker pages takes you to the Graveyard page, which says to visit the Undertaker page for more information on him - it's a continuous loop.

**Comment by MotionlessTrain** [comment]
> Intended, building and worker pages were merged to consolidate information, please look at previous closed issues

The link needs to be removed from the building page
