### ISSUE TITLE
Where is cookery in Building tool?

### ISSUE THREAD

**Issue by izaschniuu** [ldtteam/MinecoloniesWiki#1089]
## The Issue
literally nowhere

**Comment by izaschniuu** [comment]
Uploading output(compress-video-online.com).mp4…

**Comment by izaschniuu** [comment]
https://github.com/user-attachments/assets/692d2009-0e5d-420a-881e-4ce0051c5d53
Uploading output(compress-video-online.com).mp4…

**Comment by Thodor12** [comment]
Please ask questions on Discord
