### ISSUE TITLE
Buildings Page

### ISSUE THREAD

**Issue by JRAT24** [ldtteam/MinecoloniesWiki#14]
- [x] Font change - Fixed cleaning up old html code
- [ ] Activate links
- [ ] Table needs to be fixed.
- [ ] Pictures need to be added to the top for the following 5 buildings:
- - [ ] Supply Ship
- - [ ] Supply Camp
- - [ ] Town Hall
- - [ ] Citizen Hut
- - [ ] Warehouse

**Comment by Wissi** [comment]
Working on the buildings pages atm.

**Comment by Wissi** [comment]
Removing the "Buildings" page from the subnav.yml as it is not needed anymore.
Adding the "Library" in it's place.
