### ISSUE TITLE
Schematics Page

### ISSUE THREAD

**Issue by PoroUsedSnax** [ldtteam/MinecoloniesWiki#16]
- [x] Copy from live site.
- [x] Change format to github format.
- [x] Upload pics for step 2 through 5.
- [x] Update content to follow suit with the newer scan tool

**Comment by Wissi** [comment]
Schematics page done.
Copied from live site and Updated with new scan tool images, instructions and video.
Still missing perhaps a bit of info specifically on how to make a custom schematic to replace the workers huts. A youtube video would be preferred.
