### ISSUE TITLE
No Master Permission

### ISSUE THREAD

**Issue by W4RP1G369** [ldtteam/MinecoloniesWiki#252]
I cannot find a Master Permission Node in the wiki. Most Master Nodes consist of the permission node string followed by a .* to gain all the perms of that mod. Can you please add one so that me and my devs can have access to the minecolonies perm system without having to add every single perm?

**Comment by Wissi** [comment]
Heyo @W4RP1G369 
Can you make this request in the Minecolonies issue page? Your request has to be coded, it doesn't exist. it's not a Wiki issue. I'll close this and if anything changes we can reopen if needed.
@lunadragnstar
