### ISSUE TITLE
No Blacksmith?

### ISSUE THREAD

**Issue by kooky112** [ldtteam/MinecoloniesWiki#257]
I noticed in the modpack Im using, Enigmatica 2, that the blacksmith is not working, and neither are the mines. Is this something being worked on or is the modpack itself behind on versions?

**Comment by Wissi** [comment]
@kooky112 This is NOT a Wiki issue, it is clearly a modpack/version issue. Check your mods folder for version you have and check [Curse](https://minecraft.curseforge.com/projects/minecolonies/files) for latest versions we have.
