### ISSUE TITLE
No requests are received on the Clipboard

### ISSUE THREAD

**Issue by SergeyAn70** [ldtteam/MinecoloniesWiki#263]
In the clipboard are not received requests from all of the colonists. And this is probably why the connection does not work "application Builder to craft - the application of a craftsman to a resource" and as a result, the implementation of the application Builder. All the necessary recipes have been studied, but the couriers run into the empty.

**Comment by Asherslab** [comment]
this is the wiki, please take this to the minecolonies repo itself =D
