### ISSUE TITLE
Builder and Lumberjack Problem

### ISSUE THREAD

**Issue by mporter012** [ldtteam/MinecoloniesWiki#266]
Im just minding my own business and playing with the mod. All of a sudden my Lumberjack stops working, then so does my 2nd builder. It's day time, clear weather, everyone else is working. Any help please?

**Comment by Asherslab** [comment]
this is the wiki, please take this to the minecolonies repo itself =D

**Comment by mporter012** [comment]
where is it?

**Comment by Asherslab** [comment]
remove "wiki" from the url?

**Comment by mporter012** [comment]
okay thanks
