### ISSUE TITLE
builder only requesting from the warehouse not crafters.

### ISSUE THREAD

**Issue by zanetano** [ldtteam/MinecoloniesWiki#268]
when a needed item is in the warehouse the builder requests it no problem.
when the item (like stairs) needs to be crafted, the builder still wants the request to be fulfilled by the warehouse...
![Capture](https://user-images.githubusercontent.com/54339342/63394887-ae2c0f80-c3b9-11e9-867a-df56c2b4cb6f.PNG)
![Capture2](https://user-images.githubusercontent.com/54339342/63394888-ae2c0f80-c3b9-11e9-8e6f-2f60a58c5942.PNG)
The crafter knows how to make them
![Capture3](https://user-images.githubusercontent.com/54339342/63394889-ae2c0f80-c3b9-11e9-9fb1-7202dfc08d45.PNG)
and i have a crafter employed
![Capture4](https://user-images.githubusercontent.com/54339342/63394890-ae2c0f80-c3b9-11e9-9c71-24db7d176f5e.PNG)

Crafter never gets the order...

when i craft them myself and place them in the warehouse:
![Capture5](https://user-images.githubusercontent.com/54339342/63395020-3d392780-c3ba-11e9-9c4e-9c46d0d8036c.PNG)

**Comment by Asherslab** [comment]
You are in the wrong repository, this is the wiki.
https://github.com/ldtteam/Minecolonies
