### ISSUE TITLE
Cowboy hut: grass path

### ISSUE THREAD

**Issue by Zombycow** [ldtteam/MinecoloniesWiki#269]
The cowboy hut: stone requires grass paths to be given to the builder in order for him to build it. yet minecraft has no recipe for grass paths, and they cannot be picked up with silk touch.

possible solutions:

1: a new crafting recipe for grass paths requiring 1 grass and 1 shovel in the crafting grid
2: have the builder create the paths himself

**Comment by Asherslab** [comment]
Wrong place, this is the wiki repo
