### ISSUE TITLE
Supply camp and Supply ship both say you can place with build tool

### ISSUE THREAD

**Issue by Talyda** [ldtteam/MinecoloniesWiki#273]
> You can make and use the Building Tool to place the Supply Camp so you can see a 3D image and you can move it around to the exact place and orientation you want it.

That probably shouldn't be on the page, and is likely why so many people are trying to place them with the build tool and failing. In theory they shouldn't even *have* a build tool at that point int he progression.

Should be just that they click the item on the ground, that brings up a preview that they can then move around.

**Comment by Raycoms** [comment]
@lunadragnstar and @Wissi definitely this

**Comment by lunadragnstar** [comment]
Fixed
