### ISSUE TITLE
Citizens problem

### ISSUE THREAD

**Issue by Thumper52** [ldtteam/MinecoloniesWiki#276]
Citizens are appearing like ghosts, you can see right through them and they flicker.  Started a new game and they spawned in the same way.  I never had this problem before.  Not sure if it is something I'm doing or if there is a bug in the system.
![Screenshot (3)](https://user-images.githubusercontent.com/57266201/68053495-6fbca600-fcc2-11e9-89f1-9cce12c690fe.png)

**Comment by someaddons** [comment]
halloween feature, and this is for the wiki, not for the mod bugs.
