### ISSUE TITLE
Miner not using his pickaxe

### ISSUE THREAD

**Issue by Trixciel** [ldtteam/MinecoloniesWiki#281]
My miner is not using his pick. Yes i gave all the things that i should have given to him but he stills digs with his hands.

Why ?

Also about 15 seconds after he began to break the block, he takes his pick and breaks the block. 

![2020-01-01_18 15 21](https://user-images.githubusercontent.com/59417613/71644060-b29afa00-2cc2-11ea-9a71-9080ae97b79e.png)

**Comment by lunadragnstar** [comment]
This is for the Wiki, You need the mod github. https://github.com/ldtteam/minecolonies
