### ISSUE TITLE
Wiki Page error.

### ISSUE THREAD

**Issue by masternetra** [ldtteam/MinecoloniesWiki#283]
On https://wiki.minecolonies.com/source/workers/guard there is a error.

> Now you will have to issue the builder the “Build” assignment so it can build the “Farmer’s Hut”.

Error of course being the reference to the farmer's hut, since it should be referencing guard tower / barracks. Sentence should probably just be removed in it's entirely though.

**Comment by lunadragnstar** [comment]
fixed
