### ISSUE TITLE
Building Materials Requirements Book/wiki

### ISSUE THREAD

**Issue by Gibblesss** [ldtteam/MinecoloniesWiki#290]
Hello! I had an idea that might benefit a lot of people who are pro-active with building their colony. How about a book in-game or on the wiki, that shows the materials required for each level of building? So this way, while the builder(s) are working on tier 1, you can go gather the materials for tiers 2-5!

**Comment by lunadragnstar** [comment]
I'm sorry this will never happen, we have over 3000 schematics and something like that would need to be manually calculated.
