### ISSUE TITLE
Town Claim Modes Wiki page

### ISSUE THREAD

**Issue by chriskeena** [ldtteam/MinecoloniesWiki#291]
The Wiki page about Town Claim Modes doesn't reflect actual experience within the game.

Under "Configuration Options" we are told we can alter the mode in-game through "mod Options".

Within Minecraft 1.14.4 the Config button remains greyed out for Minecolonies. Not checked for other versions.

Should this be intensional the Wiki needs to be amended to reflect this.

**Comment by chriskeena** [comment]
I've now tested and the Config button works as described within 1.12.2

I was previously worried I  was looking in the wrong place.

**Comment by lunadragnstar** [comment]
Closing (added to issue #321
