### ISSUE TITLE
MINECRAFT MINECOLONIES anyone work, everyone sleeping

### ISSUE THREAD

**Issue by StewieTheBoy** [ldtteam/MinecoloniesWiki#294]
all my citizen stay at hut, the rest with houses stay at house sleeping no mater if its day or night, anyone work

**Comment by Asherslab** [comment]
1. Use The Template. it's there for a reason.

2. Have you got any weather mods installed, and are you in the overworld or another dimension?
3. Are there any messages in chat relating to why the workers might not be working?

**Comment by lunadragnstar** [comment]
This is for the Wiki, You need the mod github. https://github.com/ldtteam/minecolonies
