### ISSUE TITLE
Worker not working on Builder's Hut

### ISSUE THREAD

**Issue by Frederick117** [ldtteam/MinecoloniesWiki#295]
After trying all the steps on the troubleshooting tab i still have no success. Version 1.15.2. I placed the town hall and builder wood level 1.  After requesting to build the builder's Hut and assigning a worker, they cleared some dirt and will not proceed with (working)[building_step]. they just stand around not doing anything. I've given everyone food, the weather is clear, no blockage in their path etc. I've fired and hired every person and to no avail. this sucks... i can't even do anything past this point because i have no builder made.

**Comment by lunadragnstar** [comment]
This is for the Wiki, You need the mod github. https://github.com/ldtteam/minecolonies
