### ISSUE TITLE
Charts not aligned

### ISSUE THREAD

**Issue by ray557913** [ldtteam/MinecoloniesWiki#300]
Several charts at not aligned and just showing as a single line.  Citizen Huts has one of the and there are a couple around the pages

**Comment by ravenbuilder934** [comment]
What do you mean? The Citizen Hut page looks fine to me.

**Comment by ray557913** [comment]
That was put in almost 2 months ago, someone must have fixed it by now.

**Comment by ravenbuilder934** [comment]
@ray557913 Could you close this issue then?

**Comment by ray557913** [comment]
sure
