### ISSUE TITLE
Builder not recognizing grass = dirt

### ISSUE THREAD

**Issue by tobryin** [ldtteam/MinecoloniesWiki#301]
Looked this up online,

Builder requests grass block, cannot obtain grass block in survival, dirt is not working as a substitute (even when placed directly into builder’s personal inventory)

Will something in the configs fix this?

**Comment by Spiker985** [comment]
If you need grass, Silk Touch on Shovel will net you grass blocks. As will killing Enderman that are holding Grass blocks.

**Comment by lunadragnstar** [comment]
actually, the builder should substitute grass for dirt, if you are still having this issue, you may need to update your mod. If you are still having the issue, you need the minecolonies github https://github.com/ldtteam/minecolonies/issues
