### ISSUE TITLE
edit colonies boundries

### ISSUE THREAD

**Issue by jimbob2504** [ldtteam/MinecoloniesWiki#303]
hello, I was playing 1.15.2 and enjoying it lots but with the default size of 8x8 chunks, I quickly ran out of space so I went into the config and changed it to 13x13 and restarted the server but it didn't update it, is there a quick way to change this or do I have to start my village from scratch?

**Comment by lunadragnstar** [comment]
You can run the colony claim command, it is a bit different in 1.15 than what the wiki states at the moment but you can use tab to complete the command. Will update the wiki soon.
