### ISSUE TITLE
Builder will not upgrade space wars university

### ISSUE THREAD

**Issue by nickkoslosk** [ldtteam/MinecoloniesWiki#307]
My builder just idles instead of upgrading this building. i have tried everything on the faq page and this seems specific to this building. if you cancel the upgrade he immediately begins building the next building. builder also will start the build order but just stands wherever he is. if he is recalled he does not move, if he is nudged he walks a foot then stops and when nudged again walks to the original spot.

**Comment by nickkoslosk** [comment]
just a bit more info, builder will go and repair the building but after still will not upgrade to level 2. had a request saying items are missing but does not specify. i put every item for the building into the inventory and nothing happens. tried mc request reset and did not fix it.

**Comment by lunadragnstar** [comment]
This is the wiki issues section, you need the minecolonies github https://github.com/ldtteam/minecolonies/issues
