### ISSUE TITLE
Removing waypoints seems impossible

### ISSUE THREAD

**Issue by AydenWasTaken** [ldtteam/MinecoloniesWiki#310]
Hello,
I have googled around and looked at the official wiki, but I can't find a way to remove waypoints that are generated by the roads (or any other for that matter). The only resource I found suggested to place a block or drop a sand block in or on top of the waypoint, removing it because the waypoints supposedly can not exist within another block. I tried this and it did not work. I've basically built all my bridges and pathways with the building tool and so there are A LOT of waypoints. They also cause issues with the citizens trying to go anywhere. They seem to stop at every waypoint and "rethink" their path. Any way to remove these waypoints?
I am playing valhelsia 2 v2.1.6 with Minecolonies version 0.11.831

Thanks in advance,
Ayden

**Comment by lunadragnstar** [comment]
Sorry for the delay, yes covering the waypoint works but you have to give it 30 - 60 seconds to update.
