### ISSUE TITLE
Guard system fixes

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/MinecoloniesWiki#319]
I was thinking we could merge the Guard Tower, Barracks, Barracks Tower, Archery, and Combat Academy into one page called the Guard System, since they seem interdependent to me. We could also put the Guard, Knight, and Ranger pages there as well.

The Knight worker page doesn't show up on the dropdown menu or the list of workers (on the wiki home or the worker system page), but the Guard does. The Ranger also doesn't show up on the list of workers in the worker system page, but it does on the dropdown menu and on the wiki home.

*This is coming from someone whose world is on peaceful and doesn't have any guards, so feel free to take with a grain of salt!*

**Comment by lunadragnstar** [comment]
Closing (added to Existing issue #43 )
