### ISSUE TITLE
Wiki Pages that Need Updated

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/MinecoloniesWiki#321]
- [ ] Installation - Native Launcher
- [ ] Installation - MultiMC
- [ ] Installation - Twitch
- [ ] Tutorial - Walkthroughs
- [ ] Tutorial - Schematics
- [ ] Tutorial - Servers
- [x] Command System
- [ ] Happiness System
- [ ] WorkerSystem
- [ ] Town Claim System
- [ ] Protection System
- [ ] Scan Tool

**Comment by d34thii** [comment]
Regarding the timberframes:

How should we go about it? I see that there are recipes for a lot of the difference kinds of blocks but the old timberframealt showed just all kinds of timber frames using oak. 

So should there be a recipe for each kind of wood and it would then show each different form per wood, or should there be a recipe for each kind of timber block and each one should show the timber block per wood?

**Comment by d34thii** [comment]
Timberframes should now be complete -> #329

**Comment by Neya90** [comment]
Builders hut Teach Recipe option, is a 2x2 crafting grid , not a 3x3 grid

**Comment by ravenbuilder934** [comment]
I will update that now-sorry!

**Comment by Animusmontus** [comment]
The multi piston link on the Recipe page is not correct.

**Comment by ravenbuilder934** [comment]
#416 fixes this

**Comment by ravenbuilder934** [comment]
This has been superseded by https://github.com/ldtteam/MinecoloniesWiki/projects/2! If you find any other pages that need updating, please open a new issue.
