### ISSUE TITLE
Florist link in list of workers not working

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/MinecoloniesWiki#322]
In the Worker System page, at the bottom with the list of workers and their skills, the florist link shows up like this: 
![Capture](https://user-images.githubusercontent.com/63612548/81297855-8a892200-9039-11ea-8ef7-36c5c584b941.PNG)

And when I click on the link, it takes me to [this page](https://wiki.minecolonies.com/source/workers/) instead of the florist page. All the other links take you straight to the intended page.

**Comment by d34thii** [comment]
Will work on it, when I fixed my laptop

**Comment by ravenbuilder934** [comment]
Okay, thank you!

**Comment by d34thii** [comment]
Done!
