### ISSUE TITLE
wiki.minecolonies.com not found

### ISSUE THREAD

**Issue by AydenWasTaken** [ldtteam/MinecoloniesWiki#330]
The link in the readme (and the link google gives for almost every search result regarding Minecolonies) is not found. I know the wiki can be found [here](https://ldtteam.github.io/MinecoloniesWiki/).

**Comment by ravenbuilder934** [comment]
https://www.reddit.com/r/Minecolonies/comments/gkq0k4/minecolonies_wiki_is_unreachable/

**Comment by lunadragnstar** [comment]
The wiki on https://wiki.minecolonies.com/ is currently offline due to server, the same wiki is also hosted on github and can be found here: https://ldtteam.github.io/MinecoloniesWiki/
