### ISSUE TITLE
Forum links are different

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/MinecoloniesWiki#338]
When I go to minecolonies.com and click on Forums (in the banner on the top of the page), it takes me [here.](forums.minecolonies.com) But when I go to the wiki and do the same thing, it takes me [here.](https://www.reddit.com/r/Minecolonies/) Maybe we could add a dropdown menu?

**Comment by Asherslab** [comment]
that would be because we are phasing the forum out.

**Comment by ravenbuilder934** [comment]
Which forum? The reddit or forum.minecolonies.com?

**Comment by Asherslab** [comment]
the latter
