### ISSUE TITLE
Racks invisible inventory

### ISSUE THREAD

**Issue by Curiousity274** [ldtteam/MinecoloniesWiki#343]
On some buildings, underground from dwarf faction, items dissapear when they put them to racks. Removing racks and letting builder to rebuild doesnt help. V15.2

**Comment by ravenbuilder934** [comment]
This is for the wiki, please make an issue here: https://github.com/ldtteam/minecolonies/issues/new

**Comment by ravenbuilder934** [comment]
Please close this issue
