### ISSUE TITLE
Add documentation for the new recipe tag mechanism

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/MinecoloniesWiki#344]
I've code support for utilizing item tags for adding and removing custom recipes for the workers via https://github.com/ldtteam/minecolonies/pull/5058. This issue is to document the process and how modpack owners  and users can customize the recipes in their datapacks.

**Comment by ravenbuilder934** [comment]
Should we put this in the planned config files page? #43

**Comment by PowerSchill** [comment]
Possibly but I don't have the ability to edit that so someone would have to manually edit that issue when I am done versus just doing a PR against this issue.

**Comment by lunadragnstar** [comment]
@PowerSchill can you DM me on Discord so I can understand this better?

**Comment by ravenbuilder934** [comment]
@gattsuru is working on this

**Comment by ravenbuilder934** [comment]
This was completed in #588
