### ISSUE TITLE
Wiki page missing (Worker System page)

### ISSUE THREAD

**Issue by bugSandwich** [ldtteam/MinecoloniesWiki#346]
The drop-down menu link under Systems leads to a non-existent page.

**Comment by ravenbuilder934** [comment]
Should be fixed in #341

**Comment by bugSandwich** [comment]
Sorry, my mistake

**Comment by ravenbuilder934** [comment]
It's fine!

**Comment by jarquafelmu** [comment]
#341 hasn't been merged yet so that's why it still looks broken
