### ISSUE TITLE
Need Recipe Images

### ISSUE THREAD

**Issue by Wissi** [ldtteam/MinecoloniesWiki#35]
Need recipe images in Recipe page to either reference or copy over to each worker's page.

**Comment by PoroUsedSnax** [comment]
Referencing them might be possible but I'm not sure how to go about that, there wouldn't be a good way to copy them over as they aren't images, it's all made with code

**Comment by OrionDevelopment** [comment]
Can we not put the recipe in their own page, and IFrame it?

**Comment by PoroUsedSnax** [comment]
Wissi - The only images generated at the ones that are placed inside the crafting table like the blocks, the rest of the crafting grid is made from code but every bit of code needed would be on there but it's lengthy

Orion - That might be possible, but that would probably mean a bunch of Iframes on the recipes page, and I don't know how good that would be performance wise

**Comment by PoroUsedSnax** [comment]
@Wissi Good news, I worked something out, now you can add recipes to any page with `<recipe>recipename</recipe>` replacing the recipe name with one of those from assets/data/recipes, just the name though, not the .json part.

**Comment by Wissi** [comment]
Yes, thanks. That's perfect, best option for future use as well.
 (I'll list missing recipes here so I can keep track of what's missing and follow up as needed)
**Under Tools/Utilites:**                                                                            
- [ ]  Resource-Scroll
- [ ]  Multiblock
- [ ]  Barrel

**Under hut Blocks:**
- [ ]  Composter Hut
- [ ]  Library
