### ISSUE TITLE
Knight in Training and Ranger in Training pages look weird

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/MinecoloniesWiki#354]
The Knight in Training and Ranger in Training pages look like this, with everything inside the infobox. The code is the same as any other worker, so I don't know why it's like this.
![rangerintraining](https://user-images.githubusercontent.com/63612548/83799328-3e96c080-a66b-11ea-8c8b-bc2bc3efe413.png)
![knightintraining](https://user-images.githubusercontent.com/63612548/83799330-3f2f5700-a66b-11ea-97bb-80f9c82f3ab5.PNG)

**Comment by lunadragnstar** [comment]
I haven't had a chance to look at all your updated pages yet, they don't really show right on git so I have to put them out, then adjust the layout. It takes forever to get things just right, but I will get through them. 

It's usually just a line spacing issue.

**Comment by lunadragnstar** [comment]
Fixed
