### ISSUE TITLE
Need to add the second page of the Deliveryman's Hut GUI

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/MinecoloniesWiki#355]
The page of the Deliveryman's Hut GUI where it shows the deliveries is not on the Deliveryman's Hut page. I might fix this myself, not sure.

**Comment by lunadragnstar** [comment]
I got the gui image uploaded for that, I just haven't gotten to update the page yet

**Comment by lunadragnstar** [comment]
Fixed
