### ISSUE TITLE
Buildings advancement tree?

### ISSUE THREAD

**Issue by Yjola** [ldtteam/MinecoloniesWiki#359]
Hi there, I updatet my game to latest 15.2 version an found that some Buildings can only be build after the Universety- so are there more of those "layers" and can you give uns something like an advancement tree?

**Comment by ravenbuilder934** [comment]
@lunadragnstar How could we do this? If we can't do a graphic, maybe we could just list buildings?

**Comment by Yjola** [comment]
Maby like main buildings and reaserchable buildings.

I don't no the specifics so someting like this:

Townhall (in supply Chest)
Bilder (craft)
Lumberjack (craft)
.
.
.
University (craft)
 - - > flowershop(reaserch)
 - - > library (Research)

Im not that far in the game so i did Not finde all af them and don't know
if there are buildings that are only craftable aber reasercing and crafting
others. ( like in the old game Vinlands of ubisoft)

I just scrolled your Wiki and did 't found anything it in the buildings
descriptions.

Sry for the trubble and my bad englisch.

Stay healthy!

ravenbuilder934 <notifications@github.com> schrieb am So., 7. Juni 2020,
17:05:

**Comment by lunadragnstar** [comment]
I will be creating a build list by requirements, I just haven't gotten to it yet

**Comment by Yjola** [comment]
Than I will be waiting patiently. I don't have much time to play anyway, so
it won't feel to long.
Thank you for your hard work!

lunadragnstar <notifications@github.com> schrieb am So., 7. Juni 2020,
18:00:

**Comment by PowerSchill** [comment]
What about updating the advancements to illustrate the path required?

**Comment by lunadragnstar** [comment]
I have added the screenshots for the University Research

**Comment by lunadragnstar** [comment]
Added information to the buildings pages to tell when something needs researched and what building needs to be built.
