### ISSUE TITLE
Doc Request: Worker Level

### ISSUE THREAD

**Issue by Geoffrotism** [ldtteam/MinecoloniesWiki#364]
I scoured the docs looking for what worker levels do and it is only briefly mentioned on the tutorial page. It would be great if an explanation of what worker levels do/benefits was added to the Systems > Worker System part of the Wiki.

**Comment by ravenbuilder934** [comment]
Every building GUI description says this: Worker Assigned: Tells you the worker assigned to this building and their worker level. The worker levels up in time by working. The higher their level, the faster and more efficient they will be.

But yeah, we should probably add this to the worker system page too.
