### ISSUE TITLE
Links in the building GUI description don't work

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/MinecoloniesWiki#388]
![Annotation 2020-06-24 104731](https://user-images.githubusercontent.com/63612548/85588313-31d11100-b608-11ea-9158-5d327c9ae1f3.png)

It's the same for all the building GUI descriptions.

**Comment by ravenbuilder934** [comment]
I think this might be because it's in bullet points, as I've noticed links in other bullet point lists don't work. Not sure though.

**Comment by lunadragnstar** [comment]
Fixed

**Comment by ravenbuilder934** [comment]
Data --> GUI.yml still needs to be fixed

**Comment by ravenbuilder934** [comment]
Never mind, I just saw your commit
