### ISSUE TITLE
Need to add buttons on some hut GUI descriptions

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/MinecoloniesWiki#391]
In the GUI description of a few huts, the buttons that show the in-game help/the hut inventory including racks (like in the Warehouse) aren't explained.

**Comment by lunadragnstar** [comment]
Not sure what this means

**Comment by ravenbuilder934** [comment]
The buttons for the in-game wiki on some huts (and the button to show the entire inventory of the hut (including racks) aren't explained in the building GUI descriptions.
