### ISSUE TITLE
Fisherman

### ISSUE THREAD

**Issue by thomasTAWl** [ldtteam/MinecoloniesWiki#417]
Fisherman won’t fish just stands where he can and doesn’t do anything else. Not hungry either.
Doesn’t work with acacia building either with built in pool for him to use

**Comment by ravenbuilder934** [comment]
This repository is for the minecolonies *wiki*. Please open an issue at https://github.com/ldtteam/minecolonies/issues

**Comment by ravenbuilder934** [comment]
Please close this issue

**Comment by ravenbuilder934** [comment]
Please close this issue @thomasTAWl
