### ISSUE TITLE
Why is the guard in colony always red in my citizen stat

### ISSUE THREAD

**Issue by AndyOoi** [ldtteam/MinecoloniesWiki#426]
I have 6 guard in my colony but still the stat of my citizen (guard in the colony) still red??

**Comment by ShadowProtocol** [comment]
This is the wiki. If you have an issue with the mod, and not the information presented on the wiki, please open an issue on the [main repository](https://github.com/ldtteam/minecolonies/issues/new/choose) instead. Don't forget to fill out the issue template if you want assistance. If you have a general enquiry, ask at our [Discord](https://discord.gg/gA7T6ma) help channels.

**Comment by ravenbuilder934** [comment]
Please close this issue as well.
