### ISSUE TITLE
I need  help  about some aspects of the game 

### ISSUE THREAD

**Issue by DIANA1113** [ldtteam/MinecoloniesWiki#428]
From what I noticed on your Minecolonies Wiki page, there are several careers in college
But in my installation only COMBAT appears.
I play in 1.15.2 and finding that mood was a salvation but reading I saw that there are only certain jobs that are available if the university studies but it does not work for me and I am not sure if it is because of the version of my Minecraft or something else
I really love your Mood I hope I have answers I'm from Argentina
Thank you so much

**Comment by ravenbuilder934** [comment]
What is your MineColonies version (not Minecraft version)? You might need to update.

**Comment by DIANA1113** [comment]
The version I have downloaded is

minecolonies-0.13.81-RELEASE-universal.jar
<https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3018733>
 Descargar
<https://www.curseforge.com/minecraft/mc-mods/minecolonies/download/3018733>

<https://www.curseforge.com/minecraft/mc-mods/minecolonies/download/3018733?client=y>

**Comment by ravenbuilder934** [comment]
Update to the latest alpha, you're a few hundred versions behind. (Alphas aren't unstable, they're just minor releases.) If that doesn't fix it, open an issue [here](https://github.com/ldtteam/minecolonies/issues) as this repository is for the wiki only. (If you open an issue there, please close this one.)

**Comment by DIANA1113** [comment]
Thank you, there it is working Really thank you very much have a beautiful
day

**Comment by ravenbuilder934** [comment]
No problem. Please close this issue though.
