### ISSUE TITLE
Sickness

### ISSUE THREAD

**Issue by angus-fjara** [ldtteam/MinecoloniesWiki#429]
I can't find anything about sickness on the wiki

**Comment by ravenbuilder934** [comment]
![Annotation 2020-08-27 155606](https://user-images.githubusercontent.com/63612548/91494036-d4fb0c80-e87d-11ea-8670-347e11d1ca02.png)
(from the Hospital page)

**Comment by ravenbuilder934** [comment]
If this satisfies you, please close this issue.
