### ISSUE TITLE
Wiki Pages that need Added

### ISSUE THREAD

**Issue by Wissi** [ldtteam/MinecoloniesWiki#43]
Might make a page for:
- [ ] Request System (explaining the flow and images)
- [ ] Barbarians (their spawn requirements and where/when they will spawn)
- [ ] Pirates (spawn requirements and and where/when they will spawn as well as Ship de-spawn time)
- [ ] Egyptian Raiders 
- [ ] Vikings
- [ ] Amazons
- [ ] Guard System?
- [ ] Configuration Files 
- [ ] Bee Keeper
- [ ] Bee Keeper Hut
- [ ] Concrete Mixer
- [ ] Concrete Mixer Hut
- [ ] Rabbit Herder
- [ ] Rabbit Hutch
- [ ] Rallying Banner
- [ ] Shape Tool
- [ ] Tag Tool
- [ ] Server Tutorial
- [ ] Deco Controller
- [ ] GD Launcher Installation
- [ ] Transportation System
- [ ] Building System

**Comment by lunadragnstar** [comment]
caliper done

**Comment by lunadragnstar** [comment]
multiblock/multipiston done

**Comment by lunadragnstar** [comment]
clipboard done

**Comment by lunadragnstar** [comment]
sawmill done

**Comment by lunadragnstar** [comment]
resource scroll done

**Comment by lunadragnstar** [comment]
substitution blocks done

**Comment by lunadragnstar** [comment]
postbox created

**Comment by lunadragnstar** [comment]
waypoints done

**Comment by Tokerocraft** [comment]
Hello.

The lumberjack cuts down the galacticraft rubber wood trees, but it does not replant them, they are not on the page to deactivate them. How could it be introduced?

**Comment by lunadragnstar** [comment]
Ok, this is for a totally different thing than what you are talking about, this isn't the github issue for that.

**Comment by Asherslab** [comment]
@Tokerocraft
A) always make a new github issue for your issues, unless there is an issue that matches what your issue is.
B) This is the wrong place. you need to go the ldtteam/minecolonies

**Comment by ravenbuilder934** [comment]
What do you mean by Hut Level Requirements? If it's the materials needed for each level of a hut, maybe we could put it on each hut's page?

**Comment by lunadragnstar** [comment]
I have a list of needed blocks, (beds, furnaces, etc) that are needed for each hut when designing a style. I have the list done, I just have to get it setup.

**Comment by ravenbuilder934** [comment]
@lunadragnstar Oh, like if you want to submit a new schematic? Could you maybe put a note on there saying this is for developers/people who want to submit a hut schematic then so other mod users don't get confused and think it's what the builder needs to build each hut like I did? (If you already did, ignore this comment!)

**Comment by lunadragnstar** [comment]
not just submitting new schematics, it is for anyone who makes custom huts.

**Comment by lunadragnstar** [comment]
There is already a list on the schematics page, I just need to get it updated.

**Comment by ravenbuilder934** [comment]
@lunadragnstar Where is the schematics page? I can't find it, but I'm probably looking in the wrong place.

**Comment by lunadragnstar** [comment]
Under tutorial

**Comment by ravenbuilder934** [comment]
@lunadragnstar Oh okay, I see it now.

**Comment by ravenbuilder934** [comment]
Also the new plantation

**Comment by ravenbuilder934** [comment]
And the mechanic

**Comment by ravenbuilder934** [comment]
And the tavern

**Comment by lunadragnstar** [comment]
Added configuration file to the list, info that needs added explaination Each line in the configuration file, as well as the other files like ciitzen names etc.

**Comment by lunadragnstar** [comment]
https://github.com/ldtteam/minecolonies/issues/5025#issuecomment-630923967

**Comment by lunadragnstar** [comment]
Created new pages for the missing huts, used the bakery page as the template for the information, but have not updated each page yet, Just pasted the bakery info in for the template. Will work on that today if I can get to all of them.

**Comment by lunadragnstar** [comment]
Created new pages for the missing workers using the baker info for the template

**Comment by lunadragnstar** [comment]
Added
School - Hut
Teacher - Worker
Pupil - Children
Glassblower - Hut
Glassblower - Worker
Dyer - Hut
Dyer - Worker
Fletcher - Hut
Fletcher - Worker
Mechanic - Hut
Mechanic - Worker
Plantation - Hut
Planter - Worker
Tavern - Hut

**Comment by lunadragnstar** [comment]
@ravenbuilder934 I've added all the new huts and workers if you want to go over them and check them for me.

**Comment by ravenbuilder934** [comment]
Also new Egyptian Raiders and Vikings

**Comment by ravenbuilder934** [comment]
And #359

**Comment by ravenbuilder934** [comment]
Floating Carpet is done

**Comment by lunadragnstar** [comment]
I've been working on it for the last hr

**Comment by ravenbuilder934** [comment]
Possibly Build System?

**Comment by lunadragnstar** [comment]
What do you mean build system

**Comment by ravenbuilder934** [comment]
for building huts

**Comment by ravenbuilder934** [comment]
Deco controller page?

**Comment by lunadragnstar** [comment]
not adding the deco controller yet, until I know it works properly

**Comment by ravenbuilder934** [comment]
Transportation system page with info on minecart usage, pathing, boat usage, etc?

**Comment by ravenbuilder934** [comment]
Concrete worker and rabbit herder. Maybe also make draft pages for beekeeper, witch (type of guard), and alchemist, but don't merge them?

**Comment by ravenbuilder934** [comment]
GDLaucher installation page

**Comment by ravenbuilder934** [comment]
This has been superseded by https://github.com/ldtteam/MinecoloniesWiki/projects/2! If you find any other pages that need adding, please open a new issue.
