### ISSUE TITLE
which download link is it

### ISSUE THREAD

**Issue by ohsocorny** [ldtteam/MinecoloniesWiki#431]
I am confused about which link to download the modpack. i don't know the difference between all these beta, alpha, universal, release, official ones. I downloaded the 15.2 v2.3 version and put it in my mods folder but it didn't work.

**Comment by ravenbuilder934** [comment]
Official means it's created by us (not a knockoff). Alpha, beta, release usually indicate different levels of stability, but here they're all stable and alphas are just small releases. I _think_ universal means that it can be run on any computer/OS (as long as you have Forge), but I'm not sure.

To run modpacks, you need a launcher other than the vanilla one. Go to https://gdevs.io and download that, then click the + button in the lower left. Choose Browse Modpacks, then search for MineColonies Official. Install that and you should be good to go!

**Comment by ravenbuilder934** [comment]
By the way, next time you have a question, it would be best to ask on https://discord.minecolonies.com. If you have a bug, post on https://github.com/ldtteam/minecolonies/issues (this repository is for wiki issues only).

**Comment by ravenbuilder934** [comment]
Please close this issue.
