### ISSUE TITLE
delivery priority

### ISSUE THREAD

**Issue by DrSpectacular** [ldtteam/MinecoloniesWiki#433]
in the deliveryman/courier, could you add how the delivery priority works with the builder and stuff, cuz everything i do. the courier never/rarely delivers the stuff that the builder need, and ive tried messing with the priority settings and it doesn't work

**Comment by ravenbuilder934** [comment]
What version are you running? Also, the priority is for pickups only, not deliveries (which are automatically high priority).

**Comment by DrSpectacular** [comment]
i see well im not to sure what vertion im running but im playing a mod pack called MC eternal. but you already answered my question so thanks a lot 👍

**Comment by ravenbuilder934** [comment]
No problem.

**Comment by DrSpectacular** [comment]
> What version are you running? Also, the priority is for pickups only, not deliveries (which are automatically high priority).

but one other thing, how does the citizen recruitment work. do i just give some of them hay bales and stuff

**Comment by ravenbuilder934** [comment]
From the Tavern? If you right-click on a visitor, they should tell you what they need and have an option for you to give it to them (assuming you have it in your inventory).

**Comment by ravenbuilder934** [comment]
Also, MC Eternal is a 1.12.2 pack. 1.12.2 is not supported anymore as 1.15 and 1.16 have too many bugfixes to count, tons of new features, ~10 new workers/buildings (including the Tavern, the new way to recruit colonists), and a new building style.

**Comment by ravenbuilder934** [comment]
Please close this issue.

**Comment by ravenbuilder934** [comment]
Please close this issue
