### ISSUE TITLE
Guards Patrol distance

### ISSUE THREAD

**Issue by FaiconX** [ldtteam/MinecoloniesWiki#439]
No mention on the wiki about the increase of the guards patrol area when upgrading their tower, but there was on an old version: https://github.com/ldtteam/MinecoloniesWiki/commit/ce387baf046ded832e4b082cf154180c655364b4. I dont know if it is a bug on the mod or if it is just missing on the wiki.

**Comment by ravenbuilder934** [comment]
Might be a bug, if I remember correctly my guards patrolled my entire city when their hut was level 2-3 (okay, not that big of an area yet, but they still do the entire thing-which has gotten bigger now-when they currently have lvl 4 barracks towers)
