### ISSUE TITLE
Stone Smelter AI issue

### ISSUE THREAD

**Issue by Jackpotmans** [ldtteam/MinecoloniesWiki#447]
![bug_stonesmelter2](https://user-images.githubusercontent.com/39043011/95700131-e587fc00-0c0b-11eb-9f78-adfd15be38a8.png)
I created the stone smeltery 2 and received this error from the stone smelter.  I reseted the npc, fired and rehired and still received this message

**Comment by ravenbuilder934** [comment]
This repository is for the minecolonies *wiki.* Please open an issue at https://github.com/ldtteam/minecolonies/issues and close this one.
