### ISSUE TITLE
Right clicking a Composter Barrel with an Empty Hand Crashes the Game in 1.15.2

### ISSUE THREAD

**Issue by BestBluePenguin** [ldtteam/MinecoloniesWiki#465]
How to recreate the problem:
step 1: build a composter hut
step 2: find your composter barrel
step 3: get an empty hand
step 4: right-click it
step 5: ????
step 6: profit!

**Comment by ravenbuilder934** [comment]
This repository is for the MineColonies Wiki. Please open an issue on the main MineColonies repository: https://github.com/ldtteam/minecolonies/issues
