### ISSUE TITLE
Trading system and multiple colonies.

### ISSUE THREAD

**Issue by Russia2013** [ldtteam/MinecoloniesWiki#474]
I think it would make the mod more enjoyable if it had a configurable trading system. All items that the colony uses can be bought and sold using a currency.  In order to integrate the minecolony with other mods that have a similar aspect one could allow the exchange of emeralds for the currency. For example. Let's say the currency being used by minecolonies was the dinar.  One emerald could equal 100 dinars. To make the economy more realistic one could add a supply and demand feature. the price would go up or down based on the percentage of goods that were needed. For example if the demand for wood exceeded the supply by 10% then the cost to buy would be 10% less  and the cost to sell would be 10% more.
  It would also be ideal if one could build other colonies by buying a town hall from the mayor of the city.  Then once a player has 5 towns they could convert the area into a county that would have a count and countess who would reside in a Palatine. if the player built 5 counties then they could convert the counties into marches ruled by a marquis and his marchioness who would rule from their Marchal palace. When one would build 5 Marches one could convert it into a Duchy ruled by a Duke and a Duchess in their Duchal Palace.  Once one had 5 duchies they could create a Kingdom ruled by a King and queen from the Royal Palace.  If one was able to create 5 kingdoms they could convert it into an Empire ruled by the Emperor and Empress.  If one were to talk to the different Nobles or their clerks they could be told what their holdings demand or get quests to do things such as build a new town for one of their sons , negotiate a marriage alliance with one of their neighboring lords, or raid the holdings of a neighboring lord or arrest bandits. It would also be a great idea if there was a way to make it so once a town was established it would send it trader to neighboring markets  if they were connected by roads or ports. There could be a happiness meter which is determined by whether the people are getting their needs met. if the happiness meter is high than the people will have more children and praise their lord  if it is low they will grumble about how their lord is a a selfish idiot. If it gets too low they will revolt and if it the revolt were  successful could become a bandit haven or pirate town

**Comment by ravenbuilder934** [comment]
This repository is for the minecolonies *wiki* only. I would tell you to post at https://github.com/ldtteam/minecolonies-features/issues, but this is actually already planned :D
