### ISSUE TITLE
Fisherman doesn't do his job

### ISSUE THREAD

**Issue by ZestyBlaze** [ldtteam/MinecoloniesWiki#477]
I have a Fisherman's hut set completely up, it's got all its requirements, a 7x7x1 set of water and a fishing rod, yet he won't fish at all or even move. Furtherly, when he didn't have a rod, he wasn't asking for the rod he needed. It's like the fisherman has no AI at all

**Comment by ravenbuilder934** [comment]
This repository is for the MineColonies Wiki only. Please open an issue at https://github.com/ldtteam/minecolonies/issues
