### ISSUE TITLE
Place the schematic below Y 256

### ISSUE THREAD

**Issue by HeroCraft360** [ldtteam/MinecoloniesWiki#481]
how do i place the schematics below Y 256

**Comment by ravenbuilder934** [comment]
1. You can comment on closed issues, please do that instead of opening a new one
2. When in the build tool GUI, use the minus button to move the schematic down

**Comment by HeroCraft360** [comment]
how do i edit the height GUI in minecolonies?

**Comment by HeroCraft360** [comment]
Why does the builder in my colony say that the building is over Y 256?
And i want to build this building at my own ground level.
i dont want the builder to tell me how and where to build my building.

**Comment by ravenbuilder934** [comment]
They only say that if part of it *is* over y 256. Just like you can't build over 256, neither can the builder. So they don't let you tell them to build over y 256

**Comment by HeroCraft360** [comment]
okay thank you

**Comment by HeroCraft360** [comment]
but all of it was under y 256

**Comment by ravenbuilder934** [comment]
Hmm, what minecolonies version are you running?

**Comment by HeroCraft360** [comment]
Im sorry i went to bed onitme
i use mincolonies 1.15.2

**Comment by HeroCraft360** [comment]
i think there is some type of bug going on with 1.15.2

**Comment by ravenbuilder934** [comment]
There isn't a bug with 1.15.2, it works perfectly fine for me. I meant your specific minecolonies version, like 0.13.440 alpha (where to find this differs by launcher)

**Comment by HeroCraft360** [comment]
the reason y i said that it was bugged because they wouldnt allow me to build on ground level. they want me to build it below ground level. Like really deep before they even want to start building.

**Comment by ravenbuilder934** [comment]
Well, how high is your ground level and how tall is the schematic?

**Comment by HeroCraft360** [comment]
do you have mincraft forge 1.16.4
what is the mincraft forge you use

**Comment by HeroCraft360** [comment]
its just a  1 x  5  with 25 blocks in it .

**Comment by HeroCraft360** [comment]
and the ground levle is all flat.
i customed the world my self

**Comment by HeroCraft360** [comment]
can you just tell me the
1. Mincraft Forge
2. the mincolony verison you use

**Comment by ravenbuilder934** [comment]
Forge 31.2.36 and MineColonies 379 alpha. What Y level is your ground at?

**Comment by HeroCraft360** [comment]
what structurize did you use.

**Comment by ravenbuilder934** [comment]
94 alpha I think. What Y level is your ground at?

**Comment by HeroCraft360** [comment]
its Y 237

**Comment by ravenbuilder934** [comment]
and how tall is the schematic?

**Comment by HeroCraft360** [comment]
its just 1 chunk deep

**Comment by ravenbuilder934** [comment]
16 blocks?

**Comment by HeroCraft360** [comment]
what do you mean by how tall it is?

**Comment by ravenbuilder934** [comment]
When you place it with the build tool you'll see a white outline. How tall is the white outline in blocks?

**Comment by HeroCraft360** [comment]
the white outline shows 4 blocks deep

**Comment by ravenbuilder934** [comment]
Can you just send a screenshot of the build tool GUI when placing it?

**Comment by HeroCraft360** [comment]
alright hold up

**Comment by HeroCraft360** [comment]
its working now
thanks or all your help
i wish their was a  way i could pay you for all the things you've done for me.

**Comment by ravenbuilder934** [comment]
https://www.patreon.com/Minecolonies 😄

**Comment by HeroCraft360** [comment]
bet

**Comment by HeroCraft360** [comment]
umm what shaders do you use

**Comment by ravenbuilder934** [comment]
None, optifine breaks stuff
