### ISSUE TITLE
More Information Needed (Dimensions)

### ISSUE THREAD

**Issue by Pinkluver771** [ldtteam/MinecoloniesWiki#483]
Would it be possible to add the Length, Depth and Height of buildings on their associated pages? Including sample pictures of how they are meant to look at ground level. (Fortress Town Hall caused some confusion at Level 3 onwards.)

For Example; 
Builder's Hut, Level 5
Style: Acacia
Length: 20 Blocks
Depth: 12 Blocks
Height: 10 Blocks

**Comment by ravenbuilder934** [comment]
It's *possible,* but there are literally thousands of schematics. I'm not doing it, but if you want to, knock yourself out.

**Comment by ravenbuilder934** [comment]
(However, pages for each of the building styles, with specific information on each, might be added.)

**Comment by Pinkluver771** [comment]
I can do it myself for the stock styles provided but will need help with formatting it for the Wiki when all data is compiled.

**Comment by someaddons** [comment]
there is more than 3000 schematics

**Comment by ravenbuilder934** [comment]
Once you've done them all, you can comment here and we can discuss further
