### ISSUE TITLE
Missing Warped Buildings

### ISSUE THREAD

**Issue by Delor317** [ldtteam/MinecoloniesWiki#484]
I was laying out the city and noticed there is no shepherd, smeltery, or stone smeltery. Also is there no complimentary road design?

**Comment by ravenbuilder934** [comment]
Not the wiki's fault, I'll pass this on to the builder of the style though.

**Comment by Delor317** [comment]
sorry didn't know that was the issues for the wiki instead of for the
minecolonies. won't happen again.

**Comment by ravenbuilder934** [comment]
The buildings should be fixed now. A road style hasn't been added yet however
