### ISSUE TITLE
suggestion: List recipe types by building that produces them.

### ISSUE THREAD

**Issue by Minion0ne** [ldtteam/MinecoloniesWiki#486]
in order to help people to find the right building to make things that they need made, listing items in the description results in things getting skipped, much like a "TL;DR". by placing the items in a list form, or in a separate page specifically for the listing, it would make it easier for people to find what they are looking for without just glazing over the info.

**Comment by ravenbuilder934** [comment]
#482 might help with this once fixed

**Comment by anonymous563** [comment]
Closing because JEI does this better than we could.
