### ISSUE TITLE
midway storage rooms for miners

### ISSUE THREAD

**Issue by yggdrasil75** [ldtteam/MinecoloniesWiki#489]
the dirt rooms in vanilla mineshafts were probably temp storage rooms, might I recommend high level miners (3+) add storage rooms automatically to their shafts after a certain distance and that the deliverymen look in those rooms as well as the worker chests during pickup?

**Comment by ravenbuilder934** [comment]
This is for the wiki only, open an issue at https://github.com/ldtteam/minecolonies-features/issues
