### ISSUE TITLE
Farmers not farming

### ISSUE THREAD

**Issue by Larkenus** [ldtteam/MinecoloniesWiki#494]
I hire a farmer, but they will not harvest crops despite having several nearby fields. The farmer keeps telling me to build more fields.

**Comment by ravenbuilder934** [comment]
Did you place a field block (looks like a scarecrow)?

**Comment by Larkenus** [comment]
A builder built the fields. I tried removing and replacing the field block, but the problem persists.

**Comment by ShadowProtocol** [comment]
Firstly, please make sure you are on the latest alpha - your problem may have been solved already.
Secondly, this is the repo for the wiki, if you've found an issue with the mod and not the wiki then make an issue and **fill in the template** at https://github.com/ldtteam/minecolonies/issues/new/choose
