### ISSUE TITLE
"Build Options" GUI no longer show's "Reposition" option.

### ISSUE THREAD

**Issue by Teck1015** [ldtteam/MinecoloniesWiki#495]
In [this video](https://youtu.be/XtY3gKXBV48?t=935), at the time of upload (6 months ago), there was an option to reposition a MineColony building. However, as of November 2020, that option is no longer available.

Image of "Build Options" GUI as of November 22, 2020 
![2020-11-22_11 44 25](https://user-images.githubusercontent.com/28789740/99915793-a3e27a80-2cba-11eb-992d-40bc801ff8cd.png)

Has this option been removed or put somewhere else?

Thanks.

**Comment by ravenbuilder934** [comment]
Removed. Instead, deconstruct it, then when the builder is done go to where the deconstruct button was and click Pick Up. You'll get the hut block, which will keep its level when placing it again with the build tool.
