### ISSUE TITLE
Listing for Decorative schematics

### ISSUE THREAD

**Issue by Minion0ne** [ldtteam/MinecoloniesWiki#497]
I'd like to suggest having a listing on the wiki for the decorative schematics so that we can know what options we have without having to poke and scroll for hours. it's fun and nice seeing all the builds, but if we are looking for something specific, a listing might help us find it faster.

**Comment by anonymous563** [comment]
This is probably not feasible, so I'm going to close this for now unless someone wants to take this on their own.
