### ISSUE TITLE
Add the ressource scroll in the recipe page

### ISSUE THREAD

**Issue by webcrafter-fr** [ldtteam/MinecoloniesWiki#50]
It's all in the title.

The recipe : 

![2wiipbe](https://user-images.githubusercontent.com/7268719/48627040-d498c680-e9b3-11e8-82b5-f43128143df9.png)

**Comment by PoroUsedSnax** [comment]
Yeah, there are a few missing currently, mainly blocks, awaiting some renders from our artist when she has time, but I can get this one added I believe
