### ISSUE TITLE
Saturation System Descriptions

### ISSUE THREAD

**Issue by gattsuru** [ldtteam/MinecoloniesWiki#504]
From https://wiki.minecolonies.ldtteam.com/source/systems/happinessandsaturation

>Note: When a citizen’s hunger level gets to 0, they will head to the Restaurant to get food from the Cook. If there is no Cook, they will request in chat that you build them a Restaurant or provide them with food manually.

I'm not sure this is accurate, but I'm also not sure I understand the EntityAI logic well enough.  From a glance, EntityAIEatTask() is one of the first priorities after not-drowning and not-getting-monster'd, and in https://github.com/ldtteam/minecolonies/blob/version/1.16.3/src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java , the first logic decision of relevance is public boolean shouldEat(), which eventually checks current saturation against CitizenConstants.LOW_SATURATION (3) to eat, and if they don't have food, this eventually goes to the restaurant search patterns.

Is that correct?

> The citizen saturation system is between 0-10. If it’s 0, the citizen won’t level anymore, won’t work anymore, will request food in chat regularly, and will have the slowness effect. If it’s less than 3, the citizen won’t heal and will have a -25% leveling speed. If it’s between 3 and 5, the citizen will have a -10% leveling speed. If it’s between 5 and 7, the citizen will have a +10% leveling speed. If it’s between 7 and 10, the citizen will have a +25% leveling speed. If it’s 10, the citizen will have a double healing speed and a +25% leveling speed. They increase their saturation by eating, just like the player. Saturation is displayed with the saturation bar in each citizen’s GUI (it looks like the hunger bar in the player’s HUD).

I'm not sure all these are the case.  Doubled and zero healing speed is applied in EntityCitizen.  But while there's part of addExperience that checks for currentSaturation, but only is used if saturation if 0 or lower, not to slow or increase XP gain beyond that.

**Comment by ravenbuilder934** [comment]
This was fixed
