### ISSUE TITLE
Slate Shingle Slab??

### ISSUE THREAD

**Issue by rsmalec** [ldtteam/MinecoloniesWiki#516]
## Page(s)
Many...?

## Information Missing
I am playing 1.16.4 and my town hall upgrade is requiring "5 Slate Single Slabs".   What/where do you get slate?!  I am not using any other modpack - just vanilla Minecolonies.

**Comment by ravenbuilder934** [comment]
Make it with cobble:

![image](https://user-images.githubusercontent.com/63612548/102142603-52945980-3e28-11eb-8687-d68684e2f5bb.png)


(Screenshot taken with JEI, which I recommend installing-much better than the vanilla recipe book)
