### ISSUE TITLE
Missing Apiary and Beekeeper

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/MinecoloniesWiki#521]
## Page(s)

Under Buildings and Workers
## Information Missing

There is no mention of a bee keeper, apiary or bee tool, but they do exist.  

Unfortunately, the bee keeper complains there are no hives even if I place one in their with bees.  Please expand on this in the wiki.  Thanks!

**Comment by ravenbuilder934** [comment]
The beekeeper won't recognize the hive unless you set it with the tool. This is so they can take care of hives outside their hut area.
I will be adding these to the wiki though.
