### ISSUE TITLE
Happiness System

### ISSUE THREAD

**Issue by Talyda** [ldtteam/MinecoloniesWiki#532]
https://wiki.minecolonies.ldtteam.com/source/systems/happinessandsaturation

I'm not so sure it's inaccurate - but maybe needs more clarity?

" If 1 Guard level exists for each worker level (worker level 5 needs a Guard level 5, for example)"

Is that guard (the person) level per worker (the person) level?  Or guard (the person) per worker building level? Or even guard tower level per worker building?

**Comment by ravenbuilder934** [comment]
Person per person

**Comment by Talyda** [comment]
So a single level 15 guard (person) will keep 3 level 5 workers happy?

Do citizens still max out at level 100?  (someaddons said it was 10 per level now, so that would make 50 max?)
What's the highest level a guard can get?
Sorry, neither of those two questions have anything to do with this thing (more to do with the ridiculous amount of guards they want now)

Maybe an example that wasn't just worker level 5 needs guard level 5? Something more like Level 8 guard will keep 2 level 4 citizens happy? Although, just the link to the guard page does make it a lot clearer =) If that was there before, I missed it completely!

**Comment by ravenbuilder934** [comment]
> So a single level 15 guard (person) will keep 3 level 5 workers happy?

Yup

> Do citizens still max out at level 100?

Each of their skills maxes at 99, so I think their max level would be 49

> What's the highest level a guard can get?

Same as other workers

> the ridiculous amount of guards they want now

Yeah, the happiness increase per guard is kinda small though so it shouldn't matter *that* much

> Something more like Level 8 guard will keep 2 level 4 citizens happy?

Good idea, I'll change that
