### ISSUE TITLE
Baker hut broken

### ISSUE THREAD

**Issue by davey578** [ldtteam/MinecoloniesWiki#536]
## Description
I am new to Minecolonies. I play through cursed forge and it seems that the Baker is broken. I put down the hut and gave the person I assigned to this role some wheat. They don't do any work and just wonder around. It says in the information part to select through the GUI what you want them to make but when I try to do this there is no section in the GUI to select for them what to Bake. Also, the mine colonies Dough is not craftable. 
I am not sure what is causing this. Everything else in Minecolonies seems to work. Any feedback from the developers would be wonderful.

**Comment by ravenbuilder934** [comment]
1. This repository is for wiki issues only, in future open issues at https://github.com/ldtteam/minecolonies/issues
2. Do you mean the in-game information? That needs to be updated, I'll fix it later
3. For the Baker to work, they need to receive a request for a bakable item, either from the postbox, as a minimum stock in the warehouse, or from the cook.
4. Only the baker can craft dough, not the player.
