### ISSUE TITLE
Internal link returning 404 error

### ISSUE THREAD

**Issue by cisum3** [ldtteam/MinecoloniesWiki#546]
## Description

"https://wiki.minecolonies.ldtteam.com/source/items/gates"
this link returns 404 page not found error. Found this link under "https://wiki.minecolonies.ldtteam.com/source/systems/research" for the Technology research and the last research for the third column titled "Enhanced Gates I". The word gates is the broken link.

**Comment by ravenbuilder934** [comment]
Duplicate of #493
