### ISSUE TITLE
Smeltery

### ISSUE THREAD

**Issue by wrincewind** [ldtteam/MinecoloniesWiki#547]
## Page(s)
https://wiki.minecolonies.ldtteam.com/source/buildings/smeltery

## Inaccuracy
In-game, the achievement 'That's Oresome!' says "A level 5 smeltery has a chance of tripling every ore output, the chance is equal to the worker's level!" However, the wiki states that a level 5 smeltery's chance of ore tripling is equal to "2 x Strength Level". 

## Fix
I'm not sure which is correct - the wiki, or the in-game achievements, but one or the other needs to be re-written. I'd assume the wiki, hence my reporting it as a wiki report.

**Comment by ravenbuilder934** [comment]
Actually, right now neither are correct. Atm level 5 has the same boost as level 4, but that'll be changed soon, and I'll wait until it's changed to fix this.

**Comment by ravenbuilder934** [comment]
It's actually equal to the worker's strength level not multiplied by anything. I'm working on a fix for the wiki rn and can fix the achievement too
