### ISSUE TITLE
In game inaccurate information

### ISSUE THREAD

**Issue by AVFD** [ldtteam/MinecoloniesWiki#554]
## The Issue
In game information says: 'A level 3 Smeltery has a 100% chance of doublin ore output, nice'. That isn't the of the wiki: https://wiki.minecolonies.ldtteam.com/source/workers/smelter

-- Location --
Minecolonies Advancements.

**Comment by ravenbuilder934** [comment]
The wiki is actually correct in this case, open an issue here: https://github.com/ldtteam/minecolonies/issues
