### ISSUE TITLE
Smelter can melt tools

### ISSUE THREAD

**Issue by uecasm** [ldtteam/MinecoloniesWiki#560]
## Page(s)

https://wiki.minecolonies.ldtteam.com/source/workers/smelter
https://wiki.minecolonies.ldtteam.com/source/buildings/smeltery

## Information Missing

I discovered purely by accident yesterday that if you give the smelter some fully-repaired tools (swords, picks, etc), they will whack them a few times and (sometimes) return the head material (cobble for stone tools, gold for gold tools, etc).  They ignore damaged tools.

I assume that there is some random chance based on either the smelter or the smeltery's stats involved in whether nothing is returned, or possibly if more than one thing is returned (I only tried it out on a very low-level smelter), but I didn't test it enough to be sure either way.

This ability doesn't seem to be listed anywhere that I could find.

**Comment by gattsuru** [comment]
Looks like it's in [EntityAIWorkSmelter.java's private IAIState smeltStuff()](https://github.com/ldtteam/minecolonies/blob/version/1.16.3/src/main/java/com/minecolonies/coremod/entity/ai/citizen/smelter/EntityAIWorkSmelter.java) method.  The only random behavior I can spot is the chance of successfully extracting an enchantment (if the smelter has a vanilla Book), which scales with building level (0%, 10%, 25%, 40%, 60%).   Worker stats only impact the speed it is disassembled.

For ToolItems (pickaxe, shovel, hoe, axe) or SwordItems, it should return 1 of the repair item, if one is set.  For armor, it should return four of the repair item for feet, seven for legs, five for head, and eight for chest armor.

At least from testing, it should always return at least one item if there's a repair material set (or, for things like the Chief Sword, if it's applying an ItemTier).  If there's no repair item set, it'll return nothing.   As far as I can tell, that should be the only case where it'd return a blank item.  They will try to put the materials into their building storage near-immediately, though.

**Comment by ravenbuilder934** [comment]
Closing until the functionality is changed/fixed/removed.
