### ISSUE TITLE
 Glow effect

### ISSUE THREAD

**Issue by VtRoof** [ldtteam/MinecoloniesWiki#561]
## Page(s)
I don't understand English well, there may be mistakes, translated via google translator.

## Information Missing

My computer is very weak, on average minecraft runs at 30-40 frames per second, to fix this in the minecolonies configuration, but I follow me on NPS, the glow effect turns on and the FPS drops to 10-5, but I did not find anything there , tell me how to turn off the lighting effect when the NPC is behind you.

https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.reddit.com%2Fr%2FMinecraft%2Fcomments%2F3f89ka%2Fthe_glowing_effect_aka_spectral_arrow_effect%2F&psig=AOvVaw0YhTbeHwSB5pTu_uZXGV2o&ust=1612449837989000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPDZmvb5ze4CFQAAAAAdAAAAABAD

**Comment by ravenbuilder934** [comment]
I don't think you can, this is more of a vanilla limitation I think
