### ISSUE TITLE
Farm and Field clarification

### ISSUE THREAD

**Issue by genejg** [ldtteam/MinecoloniesWiki#562]
## Page(s)
https://wiki.minecolonies.ldtteam.com/source/buildings/farm&field

## Information Missing
For the Field, does the Farmer set down water squares, or does this need to be done by the player? (Just moved onto a more recently build after missing functionality in an older 1.12 modpack.)

**Comment by ravenbuilder934** [comment]
The farmer will not place blocks of water, only hoe.
