### ISSUE TITLE
There are no bees!

### ISSUE THREAD

**Issue by EvelynMCcol** [ldtteam/MinecoloniesWiki#566]
## Page(s)
https://wiki.minecolonies.ldtteam.com/source/buildings/apiary

## Information Missing
The Apiary is built, the beehive is linked, but the beekeeper tells me he can't find any bees. What to do about this?

**Comment by ravenbuilder934** [comment]
Find some bees and bring them to that area. The beekeeper doesn't magically create their own or anything

**Comment by EvelynMCcol** [comment]
How do you capture bees from a bees nest?

**Comment by ravenbuilder934** [comment]
You need to wait until all bees are in the nest, then use a tool enchanted with Silk Touch to break it. Placing it again will include the bees. (Source: minecraft wiki)

**Comment by EvelynMCcol** [comment]
Ah, thank you :)
