### ISSUE TITLE
Miner not mining

### ISSUE THREAD

**Issue by Samvanbogaert17** [ldtteam/MinecoloniesWiki#571]
## Description

Miner does not mine a shaft down.

What I have tried to resolve:

recall miner
restart miner
repair building
remove the entire building/shaft with cobble and rebuild the mine

All of the above but in a different location

Mine level 1
Worker level 5

Worker inventory: see attachment
minecraft 1.16.5 (All the Mods 6)
minecolonies 0.13.620-ALPHA -> upgraded from 0.13.596-ALPHA
although I noticed the issue also presented itself on numerous other versions that were RELEASE and not alpha

Am I missing something?

Anyway, thanks for the great mod, lad(s). truly one of the best mods out there

![miner inventory](https://user-images.githubusercontent.com/34511667/108524821-bf681c00-72cf-11eb-99ea-1a3bf2cb7194.jpg)

**Comment by ravenbuilder934** [comment]
This is for wiki issues only, please open an issue here https://github.com/ldtteam/minecolonies/issues
