### ISSUE TITLE
Not sure if this is inaccurate or missing - "allowPlayerSchematics" line

### ISSUE THREAD

**Issue by Talyda** [ldtteam/MinecoloniesWiki#579]
## Page(s)
https://wiki.minecolonies.ldtteam.com/source/tutorials/schematics

## Inaccuracy
This part of the page:

> How to allow my players to use their scanned decoration schematics on my server?
> Edit the configuration file and set allowPlayerSchematics to true. 

Links to the config page (https://wiki.minecolonies.ldtteam.com/source/misc/configfile) but that line for the config is in "structurize-server.toml" now and that page doesn't mention that file at all =)

**Comment by ravenbuilder934** [comment]
`For a multiplayer game, the schematics are always loaded from the world’s directory under: */minecolonies/schematics/ directory.` is also inaccurate (and related), it should be structurize/schematics
