### ISSUE TITLE
Multiplayer Bug

### ISSUE THREAD

**Issue by Jockster99** [ldtteam/MinecoloniesWiki#58]
So my friend and I are trying to play over LAN and have separate colonies, but once one town hall is placed it won't let the other person place a town hall, limiting us to one. We love this mod but would love it if this was fixed. Thanks

**Comment by Raycoms** [comment]
It is one per person and they have to be in a certain distance of each
other

**Comment by Wissi** [comment]
Not Wiki related and just got answered. Closing.
