### ISSUE TITLE
Links malfunctionning

### ISSUE THREAD

**Issue by adplantade** [ldtteam/MinecoloniesWiki#589]
## Description

On mobile, brave browser, links in the pages (not in the menu) don't redirect to the correct page : for example, clicking on "guards" in the town hall's page redirects me to the blacksmith page, even if when I hold the finger on the link, it actually displays the correct link

So far, I saw it on 
- town hall (guards -> blacksmith building)
- tavern (town hall -> chicken farmers npc)

**Comment by ravenbuilder934** [comment]
Yeah, this was actually the second part of the wiki april fool's (first part was MineColonies -> NineColonies). It's reverted now
