### ISSUE TITLE
Command usage

### ISSUE THREAD

**Issue by someaddons** [ldtteam/MinecoloniesWiki#591]
## Information Missing

We should add a part to the command page, telling the read that they are meant as Debug/admin tools and are not supposed to be part of normal gameplay. Thus they should only use them if they really know what they are doing, as there is a few which have the potential to screw the world/colony over.

**Comment by ravenbuilder934** [comment]
for all commands in general? or specific warnings for certain commands? because imo stuff like `/mc colony list` or `/mc citizens info` doesn't need a warning

**Comment by someaddons** [comment]
those are still for debug purposes right, not gameplay, so ye can just include all
