### ISSUE TITLE
Armor levels

### ISSUE THREAD

**Issue by someaddons** [ldtteam/MinecoloniesWiki#595]
## Page(s)

https://wiki.minecolonies.ldtteam.com/source/systems/worker
## Inaccuracy

Guard armor is no longer related to their level, it is now:
 leahter(0) gold(1) to chain(2) to iron(3) to diamond(4) to all(5)

and enchants give +X level, depending on the highest enchant level as usual

**Comment by ravenbuilder934** [comment]
> leahter(0)

Is the 0 the guard/barracks tower level? (For the rest too ofc)

**Comment by ravenbuilder934** [comment]
also @someaddons where does the plate armor figure into this?
