### ISSUE TITLE
Sifter page and Config page mismatch

### ISSUE THREAD

**Issue by Melriken** [ldtteam/MinecoloniesWiki#600]
## Page(s)
Sifter (and related the config file page)

## Inaccuracy
Sifter states: "However, you can change this in the config file. This also works with modded items. Anything can be added here, it is up to the player (or the server owner)." however the Config file has no such field (it was there in the 1.15 common file, but is missing in 1.16's server (and client) file(s))

related: siftermeshes appears in the config file but not on the config file page

## Fix
Bad Solution: Remove the text from the Sifter page.
Good Solution: re-add sifterdrops and siftableblocks to the Config file for the server and modify the config file wiki page to include the fields.

**Comment by ravenbuilder934** [comment]
The config page is still WIP, and the sifter page needs to be updated after the recent changes (which is on my todo list). You can now change the drops in datapacks (see their page)
