### ISSUE TITLE
New skins

### ISSUE THREAD

**Issue by zaczumba** [ldtteam/MinecoloniesWiki#602]
## Page(s)

All pages that are around villager roles
## Information Missing

In the medieval type of buildings, there are new skins that aren't shown on the website. And not just for one, but for all pages.

**Comment by ravenbuilder934** [comment]
Yeah I know, however won't be adding them as it would take up too much room on the page. If/when I add a "Building Styles" page I'd put a note on there that the medieval styles give different skins
