### ISSUE TITLE
Can't place the Supply Camp even with proper space

### ISSUE THREAD

**Issue by GordonFrmn93** [ldtteam/MinecoloniesWiki#61]
I've only been able to place it once, and that was in a superflat world with completely clean ground. The thing is, I did the exact same thing for 3 other worlds and they didn't work at all. Have any way to fix this?

**Comment by lunadragnstar** [comment]
Sorry, but this is the github for the wiki not the mod, you may want to either join the Mod discord https://discord.minecolonies.com/ or log this on the mod github https://github.com/ldtteam/Minecolonies
