### ISSUE TITLE
Second Warehouse

### ISSUE THREAD

**Issue by makjak** [ldtteam/MinecoloniesWiki#62]
Hello,
I made  change in my colony config file and in the section 
Should there be at max 1 warehouse per colony, i made it false.
After that the deliverymen confused and they only see the second warehouse.

Is there any possibility to use both of them?

Thanks in advance
Atithasos

**Comment by Raycoms** [comment]
You can use both but each dman can only serve one, so you need more dmen

**Comment by Wissi** [comment]
Also wrong Githhub. 
Closing. If there are still issues, reopen in Minecolonies and NOT in WIKI Issues.
