### ISSUE TITLE
[Improvement] Hungarian name templates

### ISSUE THREAD

**Issue by hron84** [ldtteam/MinecoloniesWiki#620]
I created a Hungarian name templates based on [this page](https://wiki.minecolonies.ldtteam.com/source/misc/customcitizennames) and I want to share it with you.

I made two versions: an accented and an unaccented one. It's because some fonts could have an issue with Hungarian ő and ű characters, but removing accent from only these characters seems... funky. In this way, everyone can choose which style fits more into their taste.

[hungarianTemplate.txt](https://github.com/ldtteam/MinecoloniesWiki/files/6412614/hungarianTemplate.txt)
[unaccHungarianTemplate.txt](https://github.com/ldtteam/MinecoloniesWiki/files/6412615/unaccHungarianTemplate.txt)

License: [CC0](https://creativecommons.org/choose/zero/)

**Comment by hron84** [comment]
Update:

 i made a mistake, lastnames was not syntactically correct array. Fixed version is here: [hungarianTemplate.txt](https://github.com/ldtteam/MinecoloniesWiki/files/6412663/hungarianTemplate.txt)

**Comment by ravenbuilder934** [comment]
Thanks, I'll add it to the templates soonish

**Comment by hron84** [comment]
I noticed right now you moved to lowercase config keys. These templates made for the older approach.
