### ISSUE TITLE
Guard page Archer information misleading

### ISSUE THREAD

**Issue by dhouck** [ldtteam/MinecoloniesWiki#623]
## The Issue
The [Guard page](https://wiki.minecolonies.ldtteam.com/source/workers/guard) says
> (Archers don’t require arrows to shoot, unless you’ve completed the research in the University.)

This is poorly worded; it reads as though archers by default don't need arrows, but once you complete research they cannot shoot without arrows.  I'm just starting with the mod and don't know the details or I'd propose an edit, but this seems wrong and a friend said that the research allows them to use arrows for extra damage when by default they can't.  There should be a better way to word this.

**Comment by ravenbuilder934** [comment]
Do you have a suggestion for the wording?

**Comment by dhouck** [comment]
As I said I'm not confident this is *correct*, but given my understanding I'd say "Archers don't require arrows to shoot, but can optionally use them for extra damage if you’ve completed the Consume Arrows research in the University".

**Comment by ravenbuilder934** [comment]
Yeah that's correct. I've changed it, thanks
