### ISSUE TITLE
Interaction of mines and guards

### ISSUE THREAD

**Issue by dhouck** [ldtteam/MinecoloniesWiki#627]
## Page(s)

https://wiki.minecolonies.ldtteam.com/source/buildings/mine

## Information Missing

In version 0.14.156-alpha (and probably earlier and later; that's just what I'm playing) the mine block has a third page for Guards.  This is completely undocumented on the wiki.

**Comment by ravenbuilder934** [comment]
Yeah, i haven't had time to work on this yet. I'll get it done soon:tm:
