### ISSUE TITLE
Fishers Hut Water needed

### ISSUE THREAD

**Issue by Brunnr** [ldtteam/MinecoloniesWiki#635]
## Page(s)

https://wiki.minecolonies.ldtteam.com/source/buildings/fisher
## Inaccuracy

It says a 7x7x1 water area is needed, but having just built the medieval spruce level 1 the water was 17 blocks wide and 13 blocks long, 3 deep except for the 2 closest rows which stepped down. So one row 1 block deep, 1 row 2 blocks deep, and 11 rows 3 blocks deep. I hope that makes sense, I found digging the pond manually really speeds up the build, so knowing how large a space is needed would help.

**Comment by ravenbuilder934** [comment]
It's at *least* 7x7x1, so larger areas are fine.
