### ISSUE TITLE
Need a page which lists all building styles IN MINECOLONIES.COM as well as their creation date

### ISSUE THREAD

**Issue by UnityRacy** [ldtteam/MinecoloniesWiki#638]
## Page Description

A page which lists all building styles IN MINECOLONIES.COM as well as their creation date
## Reason

Its a long story and well im not an English native speaker if there is anything i have offended you please forgive me and point it out to me in private
My brother and I were building a Aciacia colony on mountains and we had paved a road connected all huts in the middle though every hut was next to each other in two lines without ANY gap but there always have couriers fell off the mountain and died
After a courier and a BUILDER who were running to a construction site fell together we arrived the scene and checked the exact positions of not only those two fell but ALL deads' and we found that ALL the deads were died from fell off
Then we spawned tester to discover how they died then they took us aback because NOBODY WALKED ALONG THE ROAD BUT TOWARD THOSE WAYPOINTS INCLUDED IN DEFAULT ACIACIA SCHEMATICS
THE IMPORTANT THING IS while I was checking the waypoints my brother opened the build tool gui too and he was selecting huts then he wonder what does Asian beehouse lv5 looks like and it was only after he clicked building style scroll that we FIRST KNEW THERE IS A NEW BUILDING STYLE CALLED CALEDONIA HAD ADDED INTO 0.14
So for heavens sake PLEASE add a page which lists ALL buildling STYLES as well as their creation date in MINECOLONIES.COM so that every player could easily checks the new opportunity if any
And well im not an English native speaker if there is anything i have offended you please forgive me and point it out to me in private

**Comment by ravenbuilder934** [comment]
Please stop shouting, first of all. Second, a building style page is planned, but probably won't have the creation dates as most styles are so old nobody knows when they were first added. Thirdly, if I remember correctly there's a list of the current building styles on the build tool page

**Comment by UnityRacy** [comment]
ugh i thought i wasnt shouting though
i mean to add a page reminding "hey there IS a new style dont miss it"

**Comment by ravenbuilder934** [comment]
the changelogs already have that, and it's in the announcements on our Discord server
