### ISSUE TITLE
Outils de définition de zone

### ISSUE THREAD

**Issue by Shadow8444** [ldtteam/MinecoloniesWiki#640]
## Information Missing

Bonjour,
J'ai un soucis avec le forestier il continue de boser sur des anciennes pousse en creusant a moitié sur les nouvelles 
J'aimerais annuler le chemin crée avec l'outil de définition de zone du forestier pour la refaire au propre si possible mais actuellement je ne trouve pas comment annuler l'ancien chemin programmé avec l'outil de restrictions si vous pouvez m'aider merci :/

**Comment by ravenbuilder934** [comment]
Please join our [discord](https://discord.minecolonies.com) for support
