### ISSUE TITLE
How towers safety protection range works?

### ISSUE THREAD

**Issue by CodAngra** [ldtteam/MinecoloniesWiki#650]
## Information Missing

![2021-06-21_00 55 02](https://user-images.githubusercontent.com/86216752/122705108-713a3980-d22b-11eb-9734-bd910e3338eb.png)

**Comment by ravenbuilder934** [comment]
Fill in the template please, bit more info than just an image

**Comment by CodAngra** [comment]
Sorry I need to update it, it's the first time I use GitHub
