### ISSUE TITLE
Tag tool

### ISSUE THREAD

**Issue by GuldTasken** [ldtteam/MinecoloniesWiki#654]
## Page(s)

https://wiki.minecolonies.ldtteam.com/source/tutorials/schematics

## Information Missing

When creating custom schematics for buildings that have a function, for example... miner1 etc. There is a lack of information regarding the steps of using the tag tool to provide the necessary tags to make it function. 

There isn't a list for available tags, nor are there any extra information. For example, that the ground tag doesn't need to be at the bottom of the schematic. The mineshaft created by the miner will connect just fine without it. 

In addition, 

" Tag tool doesn't work! "
Answer:
1. Go to the official minecolonies page, 
https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/all
2. Click on the latest file (the one furthest up)
3. Read the changelog to verify structurize version. Download the latest minecolonies update.
4. Go to
https://www.curseforge.com/minecraft/mc-mods/structurize/files/all
5. Download the version of structurize that reflects the changelog of your latest minecolonies update in step 3.

**Comment by ravenbuilder934** [comment]
Added
