### ISSUE TITLE
Carpenter abilities are scalling off incorrect skills

### ISSUE THREAD

**Issue by starmun-0010** [ldtteam/MinecoloniesWiki#660]
## Page(s)
https://wiki.minecolonies.ldtteam.com/source/workers/carpenter

## Inaccuracy
From the wiki:
![image](https://user-images.githubusercontent.com/5557278/129453301-a013b54e-89c6-4a58-b0e6-6c18d2a8fedf.png)

Which makes Dexterity to be primary skill and Knowledge secondary. But from the [code](https://github.com/ldtteam/minecolonies/blob/a73d1241693d4c4aa178451a9ef86e1dfae99c5a/src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingSawmill.java#L87) in BuildingSawmill it is exatly the opposite.

```
    public Skill getPrimarySkill()
    {
        return Skill.Knowledge;
    }
    public Skill getSecondarySkill()
    {
        return Skill.Dexterity;
    }
```

I am pretty sure this is an issue with the code because semantically the skills as they are right now do not make much sense.
But the code team has asked me to open the issue here. Please look at the original issue for further details. 
https://github.com/ldtteam/minecolonies/issues/7494

## Fix
Convince the code team to correct the skills or change the description in wiki at least.

**Comment by anonymous563** [comment]
Closing this because this is not incorrect. The primary stat for the carpenter is knowledge and that increases chance to improve recipes. The secondary stat is dex and that increases crafting speed.
