### ISSUE TITLE
Tavern: Does leveling it up do anything?

### ISSUE THREAD

**Issue by dragonpaw** [ldtteam/MinecoloniesWiki#661]
## Page(s)
Tavern

## Information Missing
The page mentions that this building can only be leveled up to 3, but not what, if anything, changes depending on the level. (Is upgrading purely aesthetic, or do you get better/more visiting potential villagers?)

**Comment by ravenbuilder934** [comment]
"Upgrading the Tavern will garner more and better visitors." paragraph 2

**Comment by dragonpaw** [comment]
Ahh. I read that page like 5 times, looking for some table saying what exactly changed (like is on many other pages) and didn't see the small inline note.
