### ISSUE TITLE
Rack's craftingrecipe is not working

### ISSUE THREAD

**Issue by TaBarGul** [ldtteam/MinecoloniesWiki#679]
## Page(s)

https://wiki.minecolonies.ldtteam.com/source/items/rack
## Inaccuracy

I tried to craft the rack, but the recipe didn't work, i use with the TLauncher's 1.12.2 version. (I dont no that this problem is existing in the orignal game, but i read a redditpost, so maybe i am not alone with this. )

**Comment by ravenbuilder934** [comment]
1.12 is not supported, and the wiki is not for that version (which explains why the recipe is different). In addition piracy is not supported here
