### ISSUE TITLE
Type of wood or stone needed? 

### ISSUE THREAD

**Issue by creed333** [ldtteam/MinecoloniesWiki#683]
## Information Missing

When teaching a worker a recipe, will they only use one single type of wood/stone/metal or other material? Or are they clever enough to  substitute oak for birch or some custom wood for items that are flexible? ie, sticks can be made of any planks. Stone axes can be made of any stone. etc. The wiki doesn't say

**Comment by ravenbuilder934** [comment]
They'll use different materials, but you need to teach them the recipe for each material. For example, if you want them to make wooden axes out of either oak or birch, you'd need to teach them two separate recipes for oak and birch

**Comment by creed333** [comment]
Thanks for the quick response. I was fairly certain this was the case, but
it's hard to know for sure. I was thinking this might be a good thing to
note on the wiki. ie. that the recipe is specific to the material. Don't
teach them with something they don't have easy access to.

Also, when creating something like the rack, which recipe involves use of
the build tool, does the sawmill just cheat that tool? I assume? I haven't
tried this yet. **imagines sims running around with the power of the build
tool.. eek! 😬 **

**Comment by ravenbuilder934** [comment]
Yep, they cheat the tool for the duration of the craft and then it disappears

**Comment by creed333** [comment]
Cool, thanks!
