### ISSUE TITLE
schematic to blueprint

### ISSUE THREAD

**Issue by Howman** [ldtteam/MinecoloniesWiki#684]
## The Issue
On your wiki it use to tell you how to convert schematic to blueprint this was way back before structurize or does it do schematic case i can not get schematics to eork

**Comment by ravenbuilder934** [comment]
Where does it say how to convert .schematic to .blueprint? Structurize (and by extension minecolonies) only accepts .blueprint files

**Comment by Howman** [comment]
It use to tell you in the wiki how to convert schematic to blueprint I was wondering where that info went !

**Comment by ravenbuilder934** [comment]
Oh. Well you can't do it anymore, hence its removal

**Comment by Howman** [comment]
is there still away with an old version of Minecolonies cause i know you could and it was before there was Structurize
