### ISSUE TITLE
Pages about the smeltery and smelter claim different chances on doubling & trippling ores.

### ISSUE THREAD

**Issue by xwarockx3** [ldtteam/MinecoloniesWiki#687]
## Page(s)
Smeltery Page
Smelter Page

## Inaccuracy
The Smeltery page claims that the chance of doubling or trippling ore at the different levels is either 50% of the strength level or 100% of it.
The smelter page although claims something else, the chances are either 100% of the strength level or 200%.

## Fix
Correct the one that's wrong.

**Comment by anonymous563** [comment]
In the works. This is also for 1.16, so info about 1.18 mechanics are also being added.
