### ISSUE TITLE
New Troubleshooting Question

### ISSUE THREAD

**Issue by Rayliable** [ldtteam/MinecoloniesWiki#690]
## Page Description

A part in "Troubleshooting" for "No structures appear when attempting to place a structure."
## Reason

It's an issue I'm experiencing.

**Comment by ravenbuilder934** [comment]
Do you have Optifine? If so, this is covered under the "Missing Graphics, Issues with the Build Tool Preview, And/Or Citizen GUIs Not Opening" header
