### ISSUE TITLE
Hive style mine not working

### ISSUE THREAD

**Issue by Lolxytheslayer** [ldtteam/MinecoloniesWiki#692]
I builded level one hive styled mine and assigned a miner gived him all he needed yet he not working on closer inspecrionnhe say me mineshaft is missing proper indication is there way to fix it i am using newest version of official modpack which have newest version of minecolonies and compatible latest structurise

**Comment by ravenbuilder934** [comment]
this doesn't seem like a wiki issue, please ask on our [discord](https://discord.minecolonies.com)
