### ISSUE TITLE
Minecolonies Configuration files.

### ISSUE THREAD

**Issue by YzXupoo** [ldtteam/MinecoloniesWiki#695]
## The Issue
I have made a modpack and it's a little different then most because I am using minecolonies to make the automation process rather than machines. I am trying to alter the amount of recipes certain people in the colony can have. I can't seem to find anything in the wiki about setting or configs. 

Thank you,
-MIchael

Mrathalheim@gmail.com
(Curseforge Modpack: Infinite Crafting)

**Comment by ravenbuilder934** [comment]
the [data packs](https://wiki.minecolonies.ldtteam.com/source/tutorials/datapacks) and/or [config file](https://wiki.minecolonies.ldtteam.com/source/misc/configfile) pages might have what you need, if not I'd say this is probably more suited to our [discord](https://discord.minecolonies.com)
