### ISSUE TITLE
Add two images to the files so I can link them 

### ISSUE THREAD

**Issue by Talyda** [ldtteam/MinecoloniesWiki#699]
Want to update the shingles page, but a couple images would be useful, and I can't  upload them, so hopefully this way they can be uploaded =)

![mouseover](https://user-images.githubusercontent.com/17323101/150899173-33e6939b-14d5-4605-8ac4-cf64423407b8.PNG)

![cutter](https://user-images.githubusercontent.com/17323101/150899196-3a08e719-177d-486c-b4e2-de46058e9cde.PNG)

**Comment by ravenbuilder934** [comment]
actually you can upload them :D click the Fork button in the top right of the screen, if you have more questions dm me on discord
