### ISSUE TITLE
Bug to hire travelers from the tavern

### ISSUE THREAD

**Issue by DearGhxst** [ldtteam/MinecoloniesWiki#706]
## Description

I have tried to leave free places in the house and tavern, I have put the manual mode of assigning houses in the town hall and it keeps telling me that I do not have a place to hire. I'm using this version of mods: "minecolonies-1.16.5-1.0.352-BETA.jar" and "structurize-0.13.252-ALPHA-universal.jar"

**Comment by Talyda** [comment]
This isn't a wiki bug. Please use discord for game play issues.

Update your mod to the latest alpha, that should fix it.

**Comment by DearGhxst** [comment]
> This isn't a wiki bug. Please use discord for game play issues.
> 
> Update your mod to the latest alpha, that should fix it.

Oh sorry, and thx for help ^^
