### ISSUE TITLE
The Inventory section of a building says the worker can interract with chests and racks, while they can only see racks.

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/MinecoloniesWiki#721]
## Page(s)

The page of every buildings

## Inaccuracy
Inventory:Here you can access the hut block's storage, where the worker at this hut takes and deposits materials. They will also use any [racks](https://wiki.minecolonies.ldtteam.com/source/items/rack) or **chests** that were placed in the hut when it was built or upgraded, so be sure to check those as well!
A chest icon: Click this button to see all the items in the hut's storage (including the hut block's inventory and any racks/**chests** that came with the hut). Clicking the ? button next to an item's count will highlight the storage container it's in.

## Fix

Inventory:Here you can access the hut block's storage, where the worker at this hut takes and deposits materials. They will also use any **[racks](https://wiki.minecolonies.ldtteam.com/source/items/rack)** that were placed in the hut when it was built or upgraded, so be sure to check those as well!
A chest icon: Click this button to see all the items in the hut's storage (including the hut block's inventory and any **[racks](https://wiki.minecolonies.ldtteam.com/source/items/rack)** that came with the hut). Clicking the ? button next to an item's count will highlight the storage container it's in.

**Comment by Talyda** [comment]
Already did a PR for that while you were typing this out =)

**Comment by Talyda** [comment]
This can be closed, PR was merged =)
