### ISSUE TITLE
Information about the new Druid worker.

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/MinecoloniesWiki#731]
## Page Description

Everything about the worker

## Reason

Returning players may be confused about this new feature without a proper documentation.

**Comment by Talyda** [comment]
...the druid was released less than 2 weeks ago.
If you have some spare time, you could make the page yourself!

**Comment by Talyda** [comment]
Ren is way ahead of me!
Druid is already on the wiki!

**Comment by anonymous563** [comment]
Closing this because info is already on the wiki.
