### ISSUE TITLE
New pages for the Nether Worker and the Nether mine

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/MinecoloniesWiki#734]
## Page Description

EVERYTHING about the worker, what does it does/requires, what does it produce for the colony and the Nether mine

## Reason

New worker and new building.

**Comment by Talyda** [comment]
I think you need to learn some manners. It didn't take 2 months for info about the druid to be added - the druid was added 2 weeks ago.
I don't know exactly how you think these things work, but none of us are paid to do this. And we can't update a page about a worker when we have barely had a week to learn how the thing works ourselves.
YOU play around with it, YOU work out how it work, then YOU can make a write up for it.

**Comment by anonymous563** [comment]
Fun fact: this page is coming soon:tm:, but it's now been delayed.
