### ISSUE TITLE
Hut:Mine info missing/misleading on Max Depth

### ISSUE THREAD

**Issue by rafii6312** [ldtteam/MinecoloniesWiki#739]
## Page(s)
https://github.com/ldtteam/MinecoloniesWiki/blob/main/source/buildings/mine.md

## Information Missing
Mine Hut Block > GUI > Tab: Settings: > "Max Depth:".
Its not clear whats meant by that. By default shows "100" (-100 but not fitting in the textbox).
Confusing if "100" is the Y offset or absolute value.

Proposal:
Text to: "Max Depth Y-Level" &
increase textbox size to show "-100"
![mine1](https://user-images.githubusercontent.com/3719207/159261089-3be549fa-be64-4c5f-a958-110cbc0dd90e.PNG)
![mine2](https://user-images.githubusercontent.com/3719207/159261094-ab17cb26-731e-4a2b-b041-75b6c0ca1a25.PNG)

**Comment by anonymous563** [comment]
I agree with MotionlessTrain. This would be a better issue to post on the main Github here: https://github.com/ldtteam/minecolonies/issues/new/choose

I'm going to close this for now.
