### ISSUE TITLE
Updates to config file page

### ISSUE THREAD

**Issue by anonymous563** [ldtteam/MinecoloniesWiki#744]
## Page(s)

https://wiki.minecolonies.ldtteam.com/source/misc/configfile

## Inaccuracy

Might have changed since 1.15

**Comment by Nikademus** [comment]
Should we make a separate page for 1.18 config?

The entries currently don't quite match the setting names in the config file, do we want to match them?
Example: 
wiki - Should citizens have a middle initial?
config - usemiddleinitial

**Comment by anonymous563** [comment]
I think it would be better to do something like:
(1.18 only) spawnAbandonedColonies: spawns abandoned colonies etc... [or whatever the version-specific option is]
asianNameOrder: Prints last names first etc...
(1.16 only) otherOptionIn116Only: This option does things in 1.16.5 as a placeholder

**Comment by Nikademus** [comment]
Ok, so one page for the config file, using the actual names of the settings.  If there's a difference or version-specific setting, indicate it.
