### ISSUE TITLE
Miner wont use framed oak planks

### ISSUE THREAD

**Issue by Thulious** [ldtteam/MinecoloniesWiki#769]
## Description

Ive given the miner the framed oak plaks that he is missing. But he says he's still missing them. Tried switching the worker but without luck. Tried giving them to him and the miners hut but nothing works

**Comment by anonymous563** [comment]
1. This isn't the right place for questions like that. Try the Discord server for MineColonies.
2. This isn't a bug with the wiki.
3. You're probably not using the right materials for the framed oak planks.
