### ISSUE TITLE
Hi, I have a serious problem here...

### ISSUE THREAD

**Issue by NeSombady** [ldtteam/MinecoloniesWiki#815]
## The Issue
(I'm sorry if tex is not clear, I translated it in the translator) 
In general, I have 6 available free places to stay, but neither the children (I checked the birth control button in the town hall) nor the people who arrived at the tavern do not want to merge.
What can this be related to?
And yes, I can attach a photo, but it will be in Russian, it's one, but two, I'm afraid that you won't want to help me for obvious reasons.
Thank you in advance)

**Comment by Talyda** [comment]
This is the github for the wiki - we can't do anything for you here!

Ask on discord for help
https://discord.gg/4A5zknzu
And please mention what version of the mod you are using at the time! Thanks!

**Comment by NeSombady** [comment]
1.17. And I don't know if it matters (although it probably does) recently, both Java and the launcher on which I play have been updated.

**Comment by Talyda** [comment]
This is still the github for the wiki.
Can't help you here. And 1.17 is no longer supported

**Comment by NeSombady** [comment]
О окей. Спасибо что так бысто ответил)))

**Comment by NeSombady** [comment]
Oh okay. Thank you for responding so quickly.
