### ISSUE TITLE
Decoration Tool GUI

### ISSUE THREAD

**Issue by Nikademus** [ldtteam/MinecoloniesWiki#824]
## Page(s)
[(https://wiki.minecolonies.ldtteam.com/source/items/decocontroller)](https://wiki.minecolonies.ldtteam.com/source/items/decocontroller)

## Information Missing
Decoration Controller GUI

**Comment by MotionlessTrain** [comment]
The link to the schematics link on that page is broken as well. I guess there is something going wrong with the links on that page

**Comment by Nikademus** [comment]
I fixed the schematics link in a new PR, but there's no GUI image at all.

**Comment by anonymous563** [comment]
> I fixed the schematics link in a new PR, but there's no GUI image at all.

Actually, the fix broke it, but I just fixed it again.

**Comment by Nikademus** [comment]
The schematics link doesn't work again.

**Comment by Thodor12** [comment]
Maybe I merged it incorrectly, although I thought I had the correct new link in it
