### ISSUE TITLE
Decoration Controller Example Image Correction

### ISSUE THREAD

**Issue by KaiserThompson** [ldtteam/MinecoloniesWiki#839]
## Page(s)

https://wiki.minecolonies.ldtteam.com/source/items/decocontroller

## Information Missing

The current example image does not show that you must use "schematics/foldername/filename". The word schematics is missing from the example image.

![unknown](https://user-images.githubusercontent.com/77913954/171813178-35d17cc7-805c-480c-b224-5f456ad66837.png)

**Comment by MotionlessTrain** [comment]
That field is not large enough to make a screenshot with the entire path in it

**Comment by KaiserThompson** [comment]
Using a different schematic that does not have multiple folders will assist with clarity.

**Comment by MotionlessTrain** [comment]
I do agree that either the schematics page or the decoration page should mention that you should start the path with "schematics/", that is not entirely clear from the schematics page either

You will always end up with multiple paths, there are no upgradable decorations in the schematics folder directly and I don't recommend doing so yourself.

**Comment by KaiserThompson** [comment]
schematics/field/big would be a good example for the image even if it's not an official schematic. I understand that you can have multiple folders in the path but where that is not required to make the feature function, i believe having multiple folders in the example is unnecessary.
