### ISSUE TITLE
Structurize dependency page

### ISSUE THREAD

**Issue by anonymous563** [ldtteam/MinecoloniesWiki#842]
## Page Description

add page on structurize

**Comment by anonymous563** [comment]
includes scan tool, build tool, tag tool. anything else?

**Comment by Talyda** [comment]
Maybe something on the commands?
link session or whatever it is is one that gets asked semi-frequently and I can never remember the name of =P

**Comment by MotionlessTrain** [comment]
And the shape tool maybe?

**Comment by Thodor12** [comment]
Reopen in case you think the current page still does not satisfy
https://minecolonies.com/wiki/dependencies/structurize

**Comment by Talyda** [comment]
The links to each of the tools on that page are broken BTW
