### ISSUE TITLE
Forester's hut

### ISSUE THREAD

**Issue by Venv5** [ldtteam/MinecoloniesWiki#866]
## Page(s)
 Foresters Huts

## Inaccuracy
 will cut tree that does not have cobblestone beneth

## Fix
 delete it or whatever. The forester cuts down the trees. I got every row prepared with cobblestone and dirt.

**Comment by MotionlessTrain** [comment]
This is accurate information actually.
Though if the tree with cobblestone underneath happens to touch a tree without cobblestone underneath, the forester may assume it was one big tree, and chop it down because of that.
Also note that the cobblestone must be directly below the tree, not below the dirt the tree grows on (you should replace the dirt with cobblestone)

**Comment by Venv5** [comment]
Hi, Spryy, but since when does a tree grow on cobblestone? Regards Tanja-------- Ursprüngliche Nachricht --------Von: MotionlessTrain ***@***.***>Datum: So., 3. Juli 2022, 20:34An: ldtteam/MinecoloniesWiki ***@***.***>Cc: Venv5 ***@***.***>, Author ***@***.***>Betreff: Re: [ldtteam/MinecoloniesWiki] Forester's hut (Issue #866)
This is accurate information actually.
Though if the tree with cobblestone underneath happens to touch a tree without cobblestone underneath, the forester may assume it was one big tree, and chop it down because of that.
Also note that the cobblestone must be directly below the tree, not below the dirt the tree grows on (you should replace the dirt with cobblestone)

**Comment by MotionlessTrain** [comment]
It doesn't, that is the entire point. Trees on cobblestone (which has been placed under it manually) are seen as decorations (e.g. if you want to have a tree house, and made a custom tree for that), not as actual trees.

**Comment by Venv5** [comment]
I understand. But this information is a bit confusing. Especially for those who's native tongue isn't English and have to translate. Anyway. I hit something else. How about something like a guide build the schematics by the player? Maybe layer by layer and what is used. Tanja-------- Ursprüngliche Nachricht --------Von: MotionlessTrain ***@***.***>Datum: So., 3. Juli 2022, 20:47An: ldtteam/MinecoloniesWiki ***@***.***>Cc: Venv5 ***@***.***>, Author ***@***.***>Betreff: Re: [ldtteam/MinecoloniesWiki] Forester's hut (Issue #866)
It doesn't, that is the entire point. Trees on cobblestone (which has been placed under it manually) are seen as decorations (e.g. if you want to have a tree house, and made a custom tree for that), not as actual trees.

**Comment by MotionlessTrain** [comment]
If you want to make custom schematics yourself, you can find a tutorial on that on the wiki already [here](https://wiki.minecolonies.ldtteam.com/source/tutorials/schematics)
Otherwise, it is the intention that the builder would build it, that is why there isn't a layer-by-layer guide to help you

**Comment by Venv5** [comment]
I don't mean costum. When you got only one builder but more schematics to build you can start build e.p. The house by yourself When done you can say the builder upgrade, start build what ever. So the builder has only to say is ginished and the player won't be bored. Mit freundlichen GrüßenTanja Gleich -------- Ursprüngliche Nachricht --------Von: MotionlessTrain ***@***.***>Datum: So., 3. Juli 2022, 21:13An: ldtteam/MinecoloniesWiki ***@***.***>Cc: Venv5 ***@***.***>, Author ***@***.***>Betreff: Re: [ldtteam/MinecoloniesWiki] Forester's hut (Issue #866)
If you want to make custom schematics yourself, you can find a tutorial on that on the wiki already here
Otherwise, it is the intention that the builder would build it, that is why there isn't a layer-by-layer guide to help you

**Comment by Venv5** [comment]
Aaaah sorry. Missunderstood. OkayLast question. How to place a citizen in another house? Tanja Gleich -------- Ursprüngliche Nachricht --------Von: MotionlessTrain ***@***.***>Datum: So., 3. Juli 2022, 21:13An: ldtteam/MinecoloniesWiki ***@***.***>Cc: Venv5 ***@***.***>, Author ***@***.***>Betreff: Re: [ldtteam/MinecoloniesWiki] Forester's hut (Issue #866)
If you want to make custom schematics yourself, you can find a tutorial on that on the wiki already here
Otherwise, it is the intention that the builder would build it, that is why there isn't a layer-by-layer guide to help you

**Comment by Talyda** [comment]
This is not a support forum.
If you need help with the mod, please use discord.
