### ISSUE TITLE
Possible typo or error, Alchemist tower shows Sawmill information.

### ISSUE THREAD

**Issue by Mordekaiser7** [ldtteam/MinecoloniesWiki#870]
## Page(s)

The Alchemist Tower page
## Information Missing

It shows the leveling and recipes for Sawmill level, or is at least labeled sawmill on the chart
<img width="906" alt="4d8fb6eb6850650fd2f35c29bc5f7b7d" src="https://user-images.githubusercontent.com/108560072/178611697-4f1883da-5be9-490a-b048-91c140e9873d.png">
.

**Comment by dhouck** [comment]
Looking at the screenshots later in the page, the data table isn’t correct for the alchemist (the screenshot is from a tower that can learn 60 recipes, which isn’t a value in the table) so this isn’t just a matter of changing a few words.

**Comment by dhouck** [comment]
I do not, or I would have.  I suppose I can go digging for it; it should be easy enough to gather

**Comment by anonymous563** [comment]
The number of recipes should be accurate. Not sure where you're getting that it's not.

**Comment by Thodor12** [comment]
The reference to "Sawmill" is still wrong

**Comment by dhouck** [comment]
> The number of recipes should be accurate. Not sure where you're getting that it's not.
I’m getting it from this screenshot
![Image from wiki page showing “List of Recipes 0 of 60”](https://wiki.minecolonies.ldtteam.com/assets/images/gui/alchemistgui3.png)
60 max recipes is not anywhere on the table.

**Comment by anonymous563** [comment]
What level is that?

**Comment by MotionlessTrain** [comment]
You can get 60 recipe slots by completing a few of the researches

**Comment by dhouck** [comment]
I don’t know what level it is, but that explanation makes sense.
