### ISSUE TITLE
Include information on the guard towers page that talks about safe distance

### ISSUE THREAD

**Issue by crysallis** [ldtteam/MinecoloniesWiki#876]
When reading about a guard towers effectiveness, its shows they have a patrol distance... by level.  This is apparently  not the distance at which they make citizens feel safe. That distance is apparently based on the boarder system, which is linked, but nothing says I need to look at that for anything other than expanding my borders.  It would be nice if 
1. the patrol distance was the safety distance... or in the line that says this
Colonists like feeling safe, so building Guard Towers close to colonists’ work and homes can improve their [happiness](https://wiki.minecolonies.ldtteam.com/source/systems/happinessandsaturation).
you link to both the happiness and the border system as the patrol distance...apparently doesn't' mean anything

**Comment by Talyda** [comment]
We can't do anything to change the way to mod works, so suggesting the patrol distance become the safety radius her doesn't do anything - you could ask that as a suggestion on the minecolonies github though!

But linking to the happiness page from the guard tower page would be a good idea

**Comment by crysallis** [comment]
I'm not asking necessarily for you to update the mod lol...just have the
wiki link to the border system in such a way that the user reading the doc
on guard towers know the patrol distance doesn't mean anything and it's the
same distance that is used in the border system ... At least that's what I
was told tonight in their discord.

**Comment by Talyda** [comment]
Oh, you said it would be nice if the patrol distance was the safety distance, so I assumed you were making a suggestion to change the mod to that.
The patrol distance is still important, it doesn't mean nothing. That's why the chart is there!

**Comment by anonymous563** [comment]
I had to read this issue several times before I figured out where the confusion was, but I think this should be clearer now.
