### ISSUE TITLE
Minecolonies: postbox

### ISSUE THREAD

**Issue by Cjs1958** [ldtteam/MinecoloniesWiki#884]
## The Issue
I was looking for an answer to my question and did not find it in the given info. My question: will the "store operators" in the game interact with the postbox on their own.

**Comment by MotionlessTrain** [comment]
The [request system](https://wiki.minecolonies.ldtteam.com/source/systems/request) page should answer your question.
Only players can request at a postbox (citizens can request on their own) and only couriers can deliver items to the postbox
