### ISSUE TITLE
Dutch template for custom citizen names

### ISSUE THREAD

**Issue by VocaRainbow** [ldtteam/MinecoloniesWiki#885]
## Page Description
I'd like to contribute Dutch citizen names. I have the minecolonies-server file ready, and it works properly in Minecraft, with lots of Dutch names. I can't find a place to upload the toml file though, nothing seems to accept it. Please let me know what to do.

## Reason
Dutch is fun!

**Comment by Thodor12** [comment]
This is the repository for the wiki

**Comment by VocaRainbow** [comment]
I figured that out too late, thank you. I'll move on!

**Comment by Talyda** [comment]
We have a page on the wiki for custom names though

**Comment by Talyda** [comment]
Wouldn't you just add it to this page?
https://wiki.minecolonies.ldtteam.com/source/misc/customcitizennames

**Comment by Thodor12** [comment]
> _edits_ I think you need to create your own fork @VocaRainbow then you should be able to upload it to your fork, and create the PR to add it to that page (I still get confused with github, so I might be wrong there, but I _think_ that will work for you!)

That is correct

**Comment by VocaRainbow** [comment]
Thanks so far! My problem though is that the fork doesn't accept .toml files. Any suggestions for that?

**Comment by anonymous563** [comment]
If you make a fork of the repo to your own account, you should be able to do anything you want to it there.
As a note, the path to where you should add it is something like ~/source/misc/languageNameTemplates/dutchTemplate.toml

**Comment by Talyda** [comment]
Yeah, once you are in your fork, go to 
![image](https://user-images.githubusercontent.com/17323101/184248987-84ca0e39-5a2a-4804-a40a-087cec776df7.png)
Then click the "Add File" button, choose "upload file" and it should let you upload it there =)

**Comment by Thodor12** [comment]
Closing in favor for accepting a PR
