### ISSUE TITLE
Include distance at which the fisher can detect water to fish in

### ISSUE THREAD

**Issue by ben-dunc** [ldtteam/MinecoloniesWiki#886]
## Page(s)
[The Fisher's Hut page](https://wiki.minecolonies.ldtteam.com/source/buildings/fisher)

## Information Missing
In the fisher's hut page, there is a clause which states that the fisher's hut must be near a body of water to be able to fish. It also states that leveling up the hut increases the distance at which the fisher will detect water. However, the distance is never defined and there's no chart showing the effect on that distance when leveling up the hut like in other building pages. It would be nice to know how far the fisher can detect water so that we can know where to place it. 

In addition, it would be helpful to have info on what the chances are of catching treasure vs fish as the fisher's hut increases.

**Comment by Thodor12** [comment]
Honestly, just put it close by, the effective search range is big enough so it can always find a pool. Just make sure you actually have a pool somewhat nearby.
