### ISSUE TITLE
Forrester's page is missing `Use Shears` information

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/MinecoloniesWiki#888]
## Page(s)

Forester Settings

## Information Missing

There is no information explaining the `User Shears:` setting

**Comment by anonymous563** [comment]
1. Need to update picture
2. Need to include info on "Use Shears"

**Comment by Thodor12** [comment]
Fixed as per f5c74e214ae3229c3f1fbf851e2a3c0bbe7d39ea
