### ISSUE TITLE
Resturant will not request raw meat to cook

### ISSUE THREAD

**Issue by henrik123098** [ldtteam/MinecoloniesWiki#905]
so i have set up in the resturant a minimum stock of 1 stack of cooked beef. the warehouse have plenty of raw beef. but the cook does not request the raw beef, he request the cooked beef like its not his job to make it. which is weird.

it works fine when I request bread. the baker with request the right things and then make and bake the bread and it will get send to the restaurant. 

but anything where the cook has to cook anything raw to get the finished product he will just request the finished product instead of making it.

the clipboard even says that the solver is the player

playing version 1.18.2

**Comment by MotionlessTrain** [comment]
This is the issue tracker of the minecolonies wiki, not of the mod itself.
You can find that at https://github.com/ldtteam/minecolonies/issues
