### ISSUE TITLE
Sheperd does not do his job consciensously!

### ISSUE THREAD

**Issue by Maxwelljones** [ldtteam/MinecoloniesWiki#914]
## The Issue
The sheperd lets the sheeps out of the pen. 
(he leaves in the evening and forgets to close the fence gate)

**Comment by anonymous563** [comment]
This is the Wiki Github, not the mod's Github. However, this is known behavior. Colonists do try to close pens and doors, but there are cases where the door/pen is not closed properly. I suggest checking the [mod's main Github](https://github.com/ldtteam/minecolonies/issues) for more, or to open an issue there instead.
