### ISSUE TITLE
Worker System - Home Level <-> Max Skill Level

### ISSUE THREAD

**Issue by DarK-Zer0** [ldtteam/MinecoloniesWiki#921]
## Page(s)

Worker System
## Inaccuracy

Max Skill Levels listed no longer correspond to 1.18 Minecolonies.
## Fix

![MaxSkillLevels](https://user-images.githubusercontent.com/67623845/202739271-168ba801-cea8-4714-b54a-9985424da452.png)

**Comment by MotionlessTrain** [comment]
The formula seems to be `10 * [House Level] + 10` instead of `10 * [House Level] - 1`
