### ISSUE TITLE
Text Color

### ISSUE THREAD

**Issue by stene-m** [ldtteam/MinecoloniesWiki#923]
## The Issue
The text color on building drop down menu on main page is white.... so unreadable.

**Comment by Talyda** [comment]
Oh! Yeah, on light mode, the buildings drop down text is very unreadable!

For what it's worth, until it is fixed, if you scroll down to the bottom of the page, they are listed there too, and are readable!

**Comment by MotionlessTrain** [comment]
Not just on the main page. It uses white text on every page, so if you want to read where you want to go to you need to basically go via the main page first. (picture to clarify the issue)
![Schermafbeelding 2022-11-20 om 00 53 16](https://user-images.githubusercontent.com/6672741/202876128-a0f7947e-45a3-4ec9-bbf5-819a3abc8bae.png)

**Comment by Thodor12** [comment]
Fixed in #919
