### ISSUE TITLE
Recommend bit more info on the meta file 'pack format'

### ISSUE THREAD

**Issue by Shadizar** [ldtteam/MinecoloniesWiki#925]
## Page(s)

https://wiki.minecolonies.ldtteam.com/source/tutorials/datapacks

## Information Missing

mentions pack format 6 
better example for 1.19 would be 10 (or emphasize the way that this varies per MC version)

**Comment by Thodor12** [comment]
Fixed in 91314357f619cc5ffc33df4d1a205a14938130d4
