### ISSUE TITLE
Restaurant Bugs

### ISSUE THREAD

**Issue by astrod00d** [ldtteam/MinecoloniesWiki#928]
## Description

The Food tab and Fuel tab are blank.  The list of items that should populate on each are completely missing.  The Cook wants to know what fuel to use but there are zero to choose from.  We are playing multiplayer and I'm connecting to their server.  We're using the latest official version of Minecolonies from Curse Forge.
Minecraft Version: 1.19.2
Forge Version:  43.1.47
Modpack:  Colony Venture 1.13

**Comment by Talyda** [comment]
This is the github for the wiki, nto support.
Please use discord for support.
