### ISSUE TITLE
House changed name

### ISSUE THREAD

**Issue by TacoMuncherDude** [ldtteam/MinecoloniesWiki#939]
## Page(s)
Any page that mentions the house needs to be updated but the ones that i am aware of are starter guide at the end, and the house page itself 

## Inaccuracy
The House item/build has been changed to be called a residence

**Comment by MotionlessTrain** [comment]
Note that this is a 1.19 only change. It is still called "house" in 1.18

**Comment by Thodor12** [comment]
I will change this, but it'll be a bit more than changing just "house" to "residence". Because that yaml file does not support version specific content.
