### ISSUE TITLE
Early game items that are useful whole duration of the mod

### ISSUE THREAD

**Issue by JereNWOTFI** [ldtteam/MinecoloniesWiki#941]
## Page(s)

https://wiki.minecolonies.ldtteam.com/source/tutorials/getting-started
## Information Missing

Items called "Clipboard" and "Resource Scroll" are not advised to be crafted at any point ingame or in the wiki, while they require very few resources therefore making them really easy to make early game, and would provide a lot of quality of life features to the player early, so that they dont have to check on the NPC:s and/or builder hut all the time.

**Comment by JereNWOTFI** [comment]
Also many might not know, you can hold multiple resource scrolls if u have multiple builders, many might assume you may only have 1 scroll and attach it only to 1 builder at the time, you may just make more scrolls and view every builder with another scroll

**Comment by Thodor12** [comment]
I don't think this info is necessary, this page is more to give you a basic example of the order you'd build buildings in.
Tips are like this are best suited for in-game tutorials whenever we improve them.

**Comment by Talyda** [comment]
Ray asked them to mention it here to have it included in the guide =)
