### ISSUE TITLE
Waypoint path wrong

### ISSUE THREAD

**Issue by RobertSnype** [ldtteam/MinecoloniesWiki#942]
## Page(s)

Waypoint page.
## Inaccuracy

The waypoint info is wrong. The new change to the UI doesn't include the waypoints.
## Fix

Please include waypoints in the builder UI.

**Comment by Talyda** [comment]
Do you mean in 1.19?
if so, they are still there, you need to go into Minecolonies Original -> infrastructure -> misc (just so you can find them til thepage is updated)
