### ISSUE TITLE
schematics info 

### ISSUE THREAD

**Issue by anastasia590** [ldtteam/MinecoloniesWiki#952]
## Page(s)
 schematics 

## Inaccuracy
 the table of contents is the same for 1.19 and 1.18 and in 1.18 is not clickable so it's super-confusing as you search and search for the thing you think you need that you can't do 

## Fix
  by deleting the 1.19 only things from the TOC in 1.18 
  it would also be super-cool to have a 118 vs 1.19 paragraph like in 1.18 you can do this but in 19 you do it this way instead,  this is possible in 19 but can't be done in 18,  
    nested buildings are not mentioned at all in the wiki,  and I feel should be,  because barracks always have barracks towers,  so it's necessary to explain how parent/child buildings work -- 
       Setting an anchor block was not clear for nested buildings which have multiple hut blocks 
        Thanks for all you do!

**Comment by Thodor12** [comment]
> it would also be super-cool to have a 118 vs 1.19 paragraph like in 1.18 you can do this but in 19 you do it this way instead, this is possible in 19 but can't be done in 18,

Yeah, that's literally what the page already does, there are very minor differences in some parts.
This is a fairly recent system which has been introduced so we're still working on getting everything to use those new blocks.

As for the problem you posted that the TOC is not clickable, this is wrong. I just tested it and it works fine.
(If there is 1 specific link which doesn't work, mention that instead)

> nested buildings are not mentioned at all in the wiki, and I feel should be, because barracks always have barracks towers, so it's necessary to explain how parent/child buildings work --
Setting an anchor block was not clear for nested buildings which have multiple hut blocks

Please make a separate issue for this and do not pack it into this issue.

**Comment by MotionlessTrain** [comment]
> it would also be super-cool to have a 118 vs 1.19 paragraph like in 1.18 you can do this but in 19 you do it this way instead, this is possible in 19 but can't be done in 18

It was set up with something like that before (before the version selection was implemented), but that made it confusing for both 1.18.2 and 1.19.2 readers (it was not very clear which parts were for which version)

**Comment by Thodor12** [comment]
Like I said, those sections have been (for the most part) been taken out and replaced with version specific blocks.
However not the full page is done yet.
