### ISSUE TITLE
Ancient debris is not doubled by the smelter

### ISSUE THREAD

**Issue by DArkHekRoMaNT** [ldtteam/MinecoloniesWiki#955]
## Page(s)
[Smelter](https://wiki.minecolonies.ldtteam.com/source/workers/smelter)

## Information Missing
Ancient debris is not doubled by the smelter, like raw iron/gold/copper

**Comment by Thodor12** [comment]
Wrong repository, please file an issue at https://github.com/ldtteam/minecolonies

**Comment by DArkHekRoMaNT** [comment]
> Wrong repository, please file an issue at https://github.com/ldtteam/minecolonies

You mean Ancient Debris should smelt with fortune? Or why the main repository? I just suggest adding information about it to the wiki page
