### ISSUE TITLE
Barracks innacuracies

### ISSUE THREAD

**Issue by Talyda** [ldtteam/MinecoloniesWiki#957]
## Page(s)
https://wiki.minecolonies.ldtteam.com/source/buildings/barracks

## Inaccuracy
This line:
Each Barracks Tower can house and employ 5 Guards for a total of 20 Guards for your colony.
Should be 
Each Barracks Tower can house and employ 5 Guards for a minimum total of 20 Guards for your colony.

And the chart
Barracks Level 5, the Max # of Barracks Towers should be ...not 4. I don't know if there is a limit, I think it is unlimited.

TBH I don't know if there is a discussion needed around changing this info - not sure if the "preferred" way of doing things is still limited to 4 towers?

**Comment by Moobien** [comment]
"Each Barracks Tower can house and employ 5 Guards for a total of 20 Guards for your colony.

Each Barracks Tower houses and employes up to 5 guards depending on level. This gives you a total of 20 guards for your colony with some exceptions.

**Comment by Talyda** [comment]
No, I don't think your words help it any. If you say 'with some exceptions" you then need to state which exceptions - just adding minimum in there is enough I feel

But the chart isn't accurate strictly speaking, which is why I said it might need some discussion

**Comment by anonymous563** [comment]
Maybe "by default, each barracks will hold 4 barracks towers"?

**Comment by Moobien** [comment]
"Generally, each barracks will hold 4 barracks towers"

**Comment by Talyda** [comment]
> Or "currently, all official-style barracks will hold 4 barracks towers," then later on, "... but can have more than 4 barracks towers for custom styles"?

That sounds better actually =)

**Comment by anonymous563** [comment]
Can they have fewer than 4 barracks towers?

**Comment by Moobien** [comment]
> Can they have fewer than 4 barracks towers?

 CAN?: yes. Will it make Ray unhappy?: yes

**Comment by MotionlessTrain** [comment]
I believe Ray is unhappy wiry more than four as well
