### ISSUE TITLE
Theme info

### ISSUE THREAD

**Issue by AceDrago** [ldtteam/MinecoloniesWiki#958]
there is no info on the wiki of any kind about the theme selecting of any kind on what it effects and if it is able to change even after selecting it for the supply base or any building or if it is for the whole colony when selecting the theme or if it per building.

**Comment by Thodor12** [comment]
If you are referring to the building theme selection, there are no differences at all.
On top of that not all building themes are managed by us as a team, therefore it's not our responsibility for listing them.
