### ISSUE TITLE
Schem tutorial page has some 1.18 info on 1.19 version page

### ISSUE THREAD

**Issue by Talyda** [ldtteam/MinecoloniesWiki#960]
[## Page(s)
](https://wiki.minecolonies.ldtteam.com/source/tutorials/schematics)

## Inaccuracy
[]
This section:
(https://wiki.minecolonies.ldtteam.com/source/tutorials/schematics#how-to-create-custom-huts)
This bit of info:

> Once ready, move the myown folder into the schematics folder and start your game. You should be able to see it with the the build tool.

should say blueprints folder instead of schematics folder

And this section:
https://wiki.minecolonies.ldtteam.com/source/tutorials/schematics#how-to-allow-my-players-to-use-their-own-huts-schematics-on-my-server
This bit of info:

> You will have to copy them yourself in the schematics folder on the server and restart it.

Should also be blueprints folder instead of schematics folder

Also this link leads to no information:
https://wiki.minecolonies.ldtteam.com/source/tutorials/schematics#i-have-a-minecolonies01e6a291-8a01-4763-bcae-f3a8797b1d52cache-folder-what-is-that-for

**Comment by anonymous563** [comment]
Which version of the wiki are you on? 1.18 or 1.19?
