### ISSUE TITLE
Update Mine Y-levels

### ISSUE THREAD

**Issue by anonymous563** [ldtteam/MinecoloniesWiki#962]
## Page(s)

https://wiki.minecolonies.ldtteam.com/source/buildings/mine

## Inaccuracy

table says 1.16 y-levels

**Comment by anonymous563** [comment]
@Thodor12 Ray says you know how to look up these numbers

**Comment by Talyda** [comment]
What's wrong with the 1.16 levels?  Those numbers are accurate I thought?

**Comment by anonymous563** [comment]
1.16 isn't supported anymore, so I wanted to remove them. I also wanted to check if the 1.18 numbers worked for 1.19 as well.

**Comment by Talyda** [comment]
*is gonna go search for an old conversation*

**Comment by anonymous563** [comment]
Not removing 1.16 stuff, 1.18 is probably still right
