### ISSUE TITLE
Minimum blocks between colony borders in regards to raid spawns

### ISSUE THREAD

**Issue by wiredsalad** [ldtteam/MinecoloniesWiki#963]
## Page(s)
https://wiki.minecolonies.ldtteam.com/source/systems/raid

## Information Missing
 Notice or warning about having enough blocks between colony borders to avoid having raiders spawning in each other's colonies. An exact number of blocks isn't needed, however, an MC team member (on the official discord channel) stated that raiders spawn anywhere within an approximate number of 500 blocks from the colony. A notice in the lines of: "If in multiplayer, leave a minimum of 500 blocks between colony borders to ensure raiders don't spawn in other colonies" would then suffice. 
The consequence of not having this information means players in multiplayer settings might build too close to each other without realizing it, leaving them the issue of raiders spawning in each other's colonies. The warning for raids will show for colony A, while the attack is actually happening in colony B, resulting in colonist deaths and other unsavory things raiders leave behind.

**Comment by Thodor12** [comment]
This has become a non-issue. Raids shouldn't attack other villages anymore in case they accidently spawn somewhere in there.
