### ISSUE TITLE
Farm not working

### ISSUE THREAD

**Issue by MinnieMouse2011** [ldtteam/MinecoloniesWiki#973]
It says it ran into an AI issue and to please locate the lastest.log file or contact the server owner if playing on a server and send it to the MineColonies authors with this message. ## The Issue

**Comment by Thodor12** [comment]
Please actually include the log then

**Comment by MotionlessTrain** [comment]
Also note that this is the GitHub for bugs/inconsistencies of the wiki of minecolonies. Not the GitHub for the mod itself

**Comment by Thodor12** [comment]
> Also note that this is the GitHub for bugs/inconsistencies of the wiki of minecolonies. Not the GitHub for the mod itself

Oh, didn't even look at that xD, I will close this
