### ISSUE TITLE
Warehouse jobs

### ISSUE THREAD

**Issue by jayjaycee1** [ldtteam/MinecoloniesWiki#975]
## Page(s)
 jobs and warehouse

## Information Missing

Theres a warehouse manager (not the exact title) available at higher levels. I can’t find information on it or how to hire

**Comment by Talyda** [comment]
That's not a thing

**Comment by Thodor12** [comment]
This job doesn't exist, so this won't be added (also the relevant information about sorting is present on the warehouse page itself)
