### ISSUE TITLE
Missing "Feild" GUI

### ISSUE THREAD

**Issue by chyper111** [ldtteam/MinecoloniesWiki#977]
## Page(s)
All types of buildings are missing there feild GUI which makes planning rather difacult. Ive only noticed this in the 1.19.2 version

## Information Missing
Feild GUI

**Comment by Talyda** [comment]
What do you mean by field GUI?

**Comment by Thodor12** [comment]
I think he is reffering to https://wiki.minecolonies.ldtteam.com/source/buildings/farm, so I'm closing this issue.
