### ISSUE TITLE
Localization sound

### ISSUE THREAD

**Issue by MrDmicom** [ldtteam/MinecoloniesWiki#995]
Would you like citizens to speak in your native language? Then this is your page! All you need to do is download the required resource pack.
## Procedure
Upload the resource pack archive into the game folder, specifically into the "resourcepacks" subfolder. In the game itself, make sure to enable the resource pack.

## Resourcepacks
**Russian**
[Download Russian sound Resourcepack](https://disk.yandex.ru/d/uo9ZAKdR5f4CdA)
_Credit to Dmicom_

**Comment by Thodor12** [comment]
Fill in the issue template correctly, what page is this supposed to be and why this page need to exist?

**Comment by MrDmicom** [comment]
> Fill in the issue template correctly, what page is this supposed to be and why this page need to exist?
Sorry, I didn't see where the rules for creating a topic were.

**Comment by Talyda** [comment]
The "new page" template says to provide a description, and a reason. That's all.  They did that didn't they?

Does it really need to be under those specific two headers?

**Comment by MrDmicom** [comment]
> The "new page" template says to provide a description, and a reason. That's all. They did that didn't they?

This is my first time using GitHub, and I didn't realize right away that using templates was a requirement. Thanks for explaining it to me.

> Does it really need to be under those specific two headers?

It could be on a single page with instructions for translating the mod, covering not just the text but also names and voices. I'm really hoping that it will be available on the website in some way.

**Comment by Talyda** [comment]
Oh, sorry, I was asking Thodor, cos I was confused why it was closed, when you could have just edited the headers he wants in to your original idea =)

**Comment by MrDmicom** [comment]
> Oh, sorry, I was asking Thodor, cos I was confused why it was closed, when you could have just edited the headers he wants in to your original idea =)

I thought he closed it so I could correct the text. So he can't reopen it? 😢

**Comment by Talyda** [comment]
Hopefully he will now that you have the template followed!

**Comment by Thodor12** [comment]
@MrDmicom Can you upload the sound pack somewhere else, I will not download it from a Russian site.
