### ISSUE TITLE
Adding 1.19 info to miner page

### ISSUE THREAD

**Issue by darkbrothervs** [ldtteam/MinecoloniesWiki#997]
## Page(s)

https://wiki.minecolonies.ldtteam.com/source/workers/miner

## Information Missing

Consider adding information for 1.19+ on hut level and shaft Y-level.

**Comment by Talyda** [comment]
1.18 info is 1.18 and above

**Comment by darkbrothervs** [comment]
That's good to know.

Could the table header be changed to "1.18+" to make it more clear?

Thanks in advance.

**Comment by Talyda** [comment]
There's a button/link at the top of the page where you can edit it yourself! =)
